//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{}IdType" minOccurs="0"/>
 *         &lt;element name="Type" type="{}TypeType" minOccurs="0"/>
 *         &lt;element name="PolicyReference" type="{}PolicyReferenceType" minOccurs="0"/>
 *         &lt;element name="ProducerCode" type="{}ProducerCodeType" minOccurs="0"/>
 *         &lt;element name="CommPlanId" type="{}CommPlanIdType" minOccurs="0"/>
 *         &lt;element name="CommPlanName" type="{}CommPlanNameType" minOccurs="0"/>
 *         &lt;element name="CommPlanDesc" type="{}CommPlanDescType" minOccurs="0"/>
 *         &lt;element name="CommPlanComm" type="{}CommPlanCommType" minOccurs="0"/>
 *         &lt;element name="IsCommPlanPercent" type="{}IsCommPlanPercentType" minOccurs="0"/>
 *         &lt;element name="Commission" type="{}CommissionType" minOccurs="0"/>
 *         &lt;element name="NetCommission" type="{}NetCommissionType" minOccurs="0"/>
 *         &lt;element name="IsCommPlanTired" type="{}IsCommPlanTiredType" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{}DateCreatedType" minOccurs="0"/>
 *         &lt;element name="UserCreated" type="{}UserCreatedType" minOccurs="0"/>
 *         &lt;element name="DateModified" type="{}DateModifiedType" minOccurs="0"/>
 *         &lt;element name="UserModified" type="{}UserModifiedType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="oldValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="curValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommissionType", propOrder = {
    "content"
})
public class CommissionType {

    @XmlElementRefs({
        @XmlElementRef(name = "IsCommPlanPercent", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommPlanName", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommPlanDesc", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Type", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommPlanComm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PolicyReference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommPlanId", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IsCommPlanTired", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ProducerCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DateCreated", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UserModified", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UserCreated", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DateModified", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Commission", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NetCommission", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "oldValue")
    protected Float oldValue;
    @XmlAttribute(name = "curValue")
    protected Float curValue;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IsCommPlanPercentType }{@code >}
     * {@link JAXBElement }{@code <}{@link CommPlanNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link CommPlanDescType }{@code >}
     * {@link JAXBElement }{@code <}{@link TypeType }{@code >}
     * {@link JAXBElement }{@code <}{@link CommPlanCommType }{@code >}
     * {@link JAXBElement }{@code <}{@link PolicyReferenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link CommPlanIdType }{@code >}
     * {@link JAXBElement }{@code <}{@link IsCommPlanTiredType }{@code >}
     * {@link JAXBElement }{@code <}{@link ProducerCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateCreatedType }{@code >}
     * {@link JAXBElement }{@code <}{@link UserModifiedType }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link UserCreatedType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateModifiedType }{@code >}
     * {@link JAXBElement }{@code <}{@link CommissionType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdType }{@code >}
     * {@link JAXBElement }{@code <}{@link NetCommissionType }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the oldValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOldValue() {
        return oldValue;
    }

    /**
     * Sets the value of the oldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOldValue(Float value) {
        this.oldValue = value;
    }

    /**
     * Gets the value of the curValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCurValue() {
        return curValue;
    }

    /**
     * Sets the value of the curValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCurValue(Float value) {
        this.curValue = value;
    }

}
