//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 12:22:48 PM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{}IdType" minOccurs="0"/>
 *         &lt;element name="Type" type="{}TypeType" minOccurs="0"/>
 *         &lt;element name="PolicyReference" type="{}PolicyReferenceType" minOccurs="0"/>
 *         &lt;element name="ProducerCode" type="{}ProducerCodeType" minOccurs="0"/>
 *         &lt;element name="CommPlanId" type="{}CommPlanIdType" minOccurs="0"/>
 *         &lt;element name="CommPlanName" type="{}CommPlanNameType" minOccurs="0"/>
 *         &lt;element name="CommPlanDesc" type="{}CommPlanDescType" minOccurs="0"/>
 *         &lt;element name="CommPlanComm" type="{}CommPlanCommType" minOccurs="0"/>
 *         &lt;element name="IsCommPlanPercent" type="{}IsCommPlanPercentType" minOccurs="0"/>
 *         &lt;element name="CommissionVal" type="{}CommissionValType" minOccurs="0"/>
 *         &lt;element name="NetCommission" type="{}NetCommissionType" minOccurs="0"/>
 *         &lt;element name="IsCommPlanTired" type="{}IsCommPlanTiredType" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{}DateCreatedType" minOccurs="0"/>
 *         &lt;element name="UserCreated" type="{}UserCreatedType" minOccurs="0"/>
 *         &lt;element name="DateModified" type="{}DateModifiedType" minOccurs="0"/>
 *         &lt;element name="UserModified" type="{}UserModifiedType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="oldValue" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="curValue" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommissionType", propOrder = {
    "id",
    "type",
    "policyReference",
    "producerCode",
    "commPlanId",
    "commPlanName",
    "commPlanDesc",
    "commPlanComm",
    "isCommPlanPercent",
    "commissionVal",
    "netCommission",
    "isCommPlanTired",
    "dateCreated",
    "userCreated",
    "dateModified",
    "userModified"
})
public class CommissionType {

    @XmlElement(name = "Id")
    protected IdType id;
    @XmlElement(name = "Type")
    protected TypeType type;
    @XmlElement(name = "PolicyReference")
    protected PolicyReferenceType policyReference;
    @XmlElement(name = "ProducerCode")
    protected ProducerCodeType producerCode;
    @XmlElement(name = "CommPlanId")
    protected CommPlanIdType commPlanId;
    @XmlElement(name = "CommPlanName")
    protected CommPlanNameType commPlanName;
    @XmlElement(name = "CommPlanDesc")
    protected CommPlanDescType commPlanDesc;
    @XmlElement(name = "CommPlanComm")
    protected CommPlanCommType commPlanComm;
    @XmlElement(name = "IsCommPlanPercent")
    protected IsCommPlanPercentType isCommPlanPercent;
    @XmlElement(name = "CommissionVal")
    protected CommissionValType commissionVal;
    @XmlElement(name = "NetCommission")
    protected NetCommissionType netCommission;
    @XmlElement(name = "IsCommPlanTired")
    protected IsCommPlanTiredType isCommPlanTired;
    @XmlElement(name = "DateCreated")
    protected DateCreatedType dateCreated;
    @XmlElement(name = "UserCreated")
    protected UserCreatedType userCreated;
    @XmlElement(name = "DateModified")
    protected DateModifiedType dateModified;
    @XmlElement(name = "UserModified")
    protected UserModifiedType userModified;
    @XmlAttribute(name = "oldValue")
    protected Byte oldValue;
    @XmlAttribute(name = "curValue")
    protected Byte curValue;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setId(IdType value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeType }
     *     
     */
    public TypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeType }
     *     
     */
    public void setType(TypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the policyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyReferenceType }
     *     
     */
    public PolicyReferenceType getPolicyReference() {
        return policyReference;
    }

    /**
     * Sets the value of the policyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyReferenceType }
     *     
     */
    public void setPolicyReference(PolicyReferenceType value) {
        this.policyReference = value;
    }

    /**
     * Gets the value of the producerCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerCodeType }
     *     
     */
    public ProducerCodeType getProducerCode() {
        return producerCode;
    }

    /**
     * Sets the value of the producerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerCodeType }
     *     
     */
    public void setProducerCode(ProducerCodeType value) {
        this.producerCode = value;
    }

    /**
     * Gets the value of the commPlanId property.
     * 
     * @return
     *     possible object is
     *     {@link CommPlanIdType }
     *     
     */
    public CommPlanIdType getCommPlanId() {
        return commPlanId;
    }

    /**
     * Sets the value of the commPlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommPlanIdType }
     *     
     */
    public void setCommPlanId(CommPlanIdType value) {
        this.commPlanId = value;
    }

    /**
     * Gets the value of the commPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link CommPlanNameType }
     *     
     */
    public CommPlanNameType getCommPlanName() {
        return commPlanName;
    }

    /**
     * Sets the value of the commPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommPlanNameType }
     *     
     */
    public void setCommPlanName(CommPlanNameType value) {
        this.commPlanName = value;
    }

    /**
     * Gets the value of the commPlanDesc property.
     * 
     * @return
     *     possible object is
     *     {@link CommPlanDescType }
     *     
     */
    public CommPlanDescType getCommPlanDesc() {
        return commPlanDesc;
    }

    /**
     * Sets the value of the commPlanDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommPlanDescType }
     *     
     */
    public void setCommPlanDesc(CommPlanDescType value) {
        this.commPlanDesc = value;
    }

    /**
     * Gets the value of the commPlanComm property.
     * 
     * @return
     *     possible object is
     *     {@link CommPlanCommType }
     *     
     */
    public CommPlanCommType getCommPlanComm() {
        return commPlanComm;
    }

    /**
     * Sets the value of the commPlanComm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommPlanCommType }
     *     
     */
    public void setCommPlanComm(CommPlanCommType value) {
        this.commPlanComm = value;
    }

    /**
     * Gets the value of the isCommPlanPercent property.
     * 
     * @return
     *     possible object is
     *     {@link IsCommPlanPercentType }
     *     
     */
    public IsCommPlanPercentType getIsCommPlanPercent() {
        return isCommPlanPercent;
    }

    /**
     * Sets the value of the isCommPlanPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsCommPlanPercentType }
     *     
     */
    public void setIsCommPlanPercent(IsCommPlanPercentType value) {
        this.isCommPlanPercent = value;
    }

    /**
     * Gets the value of the commissionVal property.
     * 
     * @return
     *     possible object is
     *     {@link CommissionValType }
     *     
     */
    public CommissionValType getCommissionVal() {
        return commissionVal;
    }

    /**
     * Sets the value of the commissionVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommissionValType }
     *     
     */
    public void setCommissionVal(CommissionValType value) {
        this.commissionVal = value;
    }

    /**
     * Gets the value of the netCommission property.
     * 
     * @return
     *     possible object is
     *     {@link NetCommissionType }
     *     
     */
    public NetCommissionType getNetCommission() {
        return netCommission;
    }

    /**
     * Sets the value of the netCommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetCommissionType }
     *     
     */
    public void setNetCommission(NetCommissionType value) {
        this.netCommission = value;
    }

    /**
     * Gets the value of the isCommPlanTired property.
     * 
     * @return
     *     possible object is
     *     {@link IsCommPlanTiredType }
     *     
     */
    public IsCommPlanTiredType getIsCommPlanTired() {
        return isCommPlanTired;
    }

    /**
     * Sets the value of the isCommPlanTired property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsCommPlanTiredType }
     *     
     */
    public void setIsCommPlanTired(IsCommPlanTiredType value) {
        this.isCommPlanTired = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link DateCreatedType }
     *     
     */
    public DateCreatedType getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCreatedType }
     *     
     */
    public void setDateCreated(DateCreatedType value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link UserCreatedType }
     *     
     */
    public UserCreatedType getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserCreatedType }
     *     
     */
    public void setUserCreated(UserCreatedType value) {
        this.userCreated = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link DateModifiedType }
     *     
     */
    public DateModifiedType getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateModifiedType }
     *     
     */
    public void setDateModified(DateModifiedType value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the userModified property.
     * 
     * @return
     *     possible object is
     *     {@link UserModifiedType }
     *     
     */
    public UserModifiedType getUserModified() {
        return userModified;
    }

    /**
     * Sets the value of the userModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserModifiedType }
     *     
     */
    public void setUserModified(UserModifiedType value) {
        this.userModified = value;
    }

    /**
     * Gets the value of the oldValue property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getOldValue() {
        return oldValue;
    }

    /**
     * Sets the value of the oldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setOldValue(Byte value) {
        this.oldValue = value;
    }

    /**
     * Gets the value of the curValue property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCurValue() {
        return curValue;
    }

    /**
     * Sets the value of the curValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCurValue(Byte value) {
        this.curValue = value;
    }

}
