//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyReference" type="{}PolicyReferenceType"/>
 *         &lt;element name="CoveragePartReference" type="{}CoveragePartReferenceType"/>
 *         &lt;element name="Formnumber" type="{}FormnumberType"/>
 *         &lt;element name="FormEditiondate" type="{}FormEditiondateType"/>
 *         &lt;element name="UserDeleteOverride" type="{}UserDeleteOverrideType"/>
 *         &lt;element name="ManualAttach" type="{}ManualAttachType"/>
 *         &lt;element name="EntityType" type="{}EntityTypeType"/>
 *         &lt;element name="Rank" type="{}RankType"/>
 *         &lt;element name="Include" type="{}IncludeType"/>
 *         &lt;element name="formDateCreated" type="{}formDateCreatedType"/>
 *         &lt;element name="formDateModified" type="{}formDateModifiedType"/>
 *         &lt;element name="UserCreated" type="{}UserCreatedType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AuditFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormType", propOrder = {
    "policyReference",
    "coveragePartReference",
    "formnumber",
    "formEditiondate",
    "userDeleteOverride",
    "manualAttach",
    "entityType",
    "rank",
    "include",
    "formDateCreated",
    "formDateModified",
    "userCreated"
})
public class FormType {

    @XmlElement(name = "PolicyReference", required = true)
    protected PolicyReferenceType policyReference;
    @XmlElement(name = "CoveragePartReference", required = true)
    protected CoveragePartReferenceType coveragePartReference;
    @XmlElement(name = "Formnumber", required = true)
    protected FormnumberType formnumber;
    @XmlElement(name = "FormEditiondate", required = true)
    protected FormEditiondateType formEditiondate;
    @XmlElement(name = "UserDeleteOverride", required = true)
    protected UserDeleteOverrideType userDeleteOverride;
    @XmlElement(name = "ManualAttach", required = true)
    protected ManualAttachType manualAttach;
    @XmlElement(name = "EntityType", required = true)
    protected EntityTypeType entityType;
    @XmlElement(name = "Rank", required = true)
    protected RankType rank;
    @XmlElement(name = "Include", required = true)
    protected IncludeType include;
    @XmlElement(required = true)
    protected FormDateCreatedType formDateCreated;
    @XmlElement(required = true)
    protected FormDateModifiedType formDateModified;
    @XmlElement(name = "UserCreated", required = true)
    protected UserCreatedType userCreated;
    @XmlAttribute(name = "AuditFlag")
    protected String auditFlag;

    /**
     * Gets the value of the policyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyReferenceType }
     *     
     */
    public PolicyReferenceType getPolicyReference() {
        return policyReference;
    }

    /**
     * Sets the value of the policyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyReferenceType }
     *     
     */
    public void setPolicyReference(PolicyReferenceType value) {
        this.policyReference = value;
    }

    /**
     * Gets the value of the coveragePartReference property.
     * 
     * @return
     *     possible object is
     *     {@link CoveragePartReferenceType }
     *     
     */
    public CoveragePartReferenceType getCoveragePartReference() {
        return coveragePartReference;
    }

    /**
     * Sets the value of the coveragePartReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoveragePartReferenceType }
     *     
     */
    public void setCoveragePartReference(CoveragePartReferenceType value) {
        this.coveragePartReference = value;
    }

    /**
     * Gets the value of the formnumber property.
     * 
     * @return
     *     possible object is
     *     {@link FormnumberType }
     *     
     */
    public FormnumberType getFormnumber() {
        return formnumber;
    }

    /**
     * Sets the value of the formnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormnumberType }
     *     
     */
    public void setFormnumber(FormnumberType value) {
        this.formnumber = value;
    }

    /**
     * Gets the value of the formEditiondate property.
     * 
     * @return
     *     possible object is
     *     {@link FormEditiondateType }
     *     
     */
    public FormEditiondateType getFormEditiondate() {
        return formEditiondate;
    }

    /**
     * Sets the value of the formEditiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormEditiondateType }
     *     
     */
    public void setFormEditiondate(FormEditiondateType value) {
        this.formEditiondate = value;
    }

    /**
     * Gets the value of the userDeleteOverride property.
     * 
     * @return
     *     possible object is
     *     {@link UserDeleteOverrideType }
     *     
     */
    public UserDeleteOverrideType getUserDeleteOverride() {
        return userDeleteOverride;
    }

    /**
     * Sets the value of the userDeleteOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDeleteOverrideType }
     *     
     */
    public void setUserDeleteOverride(UserDeleteOverrideType value) {
        this.userDeleteOverride = value;
    }

    /**
     * Gets the value of the manualAttach property.
     * 
     * @return
     *     possible object is
     *     {@link ManualAttachType }
     *     
     */
    public ManualAttachType getManualAttach() {
        return manualAttach;
    }

    /**
     * Sets the value of the manualAttach property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManualAttachType }
     *     
     */
    public void setManualAttach(ManualAttachType value) {
        this.manualAttach = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityTypeType }
     *     
     */
    public EntityTypeType getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityTypeType }
     *     
     */
    public void setEntityType(EntityTypeType value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link RankType }
     *     
     */
    public RankType getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link RankType }
     *     
     */
    public void setRank(RankType value) {
        this.rank = value;
    }

    /**
     * Gets the value of the include property.
     * 
     * @return
     *     possible object is
     *     {@link IncludeType }
     *     
     */
    public IncludeType getInclude() {
        return include;
    }

    /**
     * Sets the value of the include property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludeType }
     *     
     */
    public void setInclude(IncludeType value) {
        this.include = value;
    }

    /**
     * Gets the value of the formDateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link FormDateCreatedType }
     *     
     */
    public FormDateCreatedType getFormDateCreated() {
        return formDateCreated;
    }

    /**
     * Sets the value of the formDateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormDateCreatedType }
     *     
     */
    public void setFormDateCreated(FormDateCreatedType value) {
        this.formDateCreated = value;
    }

    /**
     * Gets the value of the formDateModified property.
     * 
     * @return
     *     possible object is
     *     {@link FormDateModifiedType }
     *     
     */
    public FormDateModifiedType getFormDateModified() {
        return formDateModified;
    }

    /**
     * Sets the value of the formDateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormDateModifiedType }
     *     
     */
    public void setFormDateModified(FormDateModifiedType value) {
        this.formDateModified = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link UserCreatedType }
     *     
     */
    public UserCreatedType getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserCreatedType }
     *     
     */
    public void setUserCreated(UserCreatedType value) {
        this.userCreated = value;
    }

    /**
     * Gets the value of the auditFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditFlag() {
        return auditFlag;
    }

    /**
     * Sets the value of the auditFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditFlag(String value) {
        this.auditFlag = value;
    }

}
