//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstallmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstallmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyReference" type="{}PolicyReferenceType"/>
 *         &lt;element name="InstallmentId" type="{}InstallmentIdType"/>
 *         &lt;element name="DisplayInstallmentId" type="{}DisplayInstallmentIdType"/>
 *         &lt;element name="PaymentPlanId" type="{}PaymentPlanIdType"/>
 *         &lt;element name="Amount" type="{}AmountType"/>
 *         &lt;element name="DueDate" type="{}DueDateType"/>
 *         &lt;element name="SendDate" type="{}SendDateType"/>
 *         &lt;element name="PaymentPlanDescription" type="{}PaymentPlanDescriptionType"/>
 *         &lt;element name="SurchargeAssessAmount" type="{}SurchargeAssessAmountType"/>
 *         &lt;element name="DateCreated" type="{}DateCreatedType"/>
 *         &lt;element name="UserCreated" type="{}UserCreatedType"/>
 *         &lt;element name="PaymentPlanCode" type="{}PaymentPlanCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallmentType", propOrder = {
    "policyReference",
    "installmentId",
    "displayInstallmentId",
    "paymentPlanId",
    "amount",
    "dueDate",
    "sendDate",
    "paymentPlanDescription",
    "surchargeAssessAmount",
    "dateCreated",
    "userCreated",
    "paymentPlanCode"
})
public class InstallmentType {

    @XmlElement(name = "PolicyReference", required = true)
    protected PolicyReferenceType policyReference;
    @XmlElement(name = "InstallmentId", required = true)
    protected InstallmentIdType installmentId;
    @XmlElement(name = "DisplayInstallmentId", required = true)
    protected DisplayInstallmentIdType displayInstallmentId;
    @XmlElement(name = "PaymentPlanId", required = true)
    protected PaymentPlanIdType paymentPlanId;
    @XmlElement(name = "Amount", required = true)
    protected AmountType amount;
    @XmlElement(name = "DueDate", required = true)
    protected DueDateType dueDate;
    @XmlElement(name = "SendDate", required = true)
    protected SendDateType sendDate;
    @XmlElement(name = "PaymentPlanDescription", required = true)
    protected PaymentPlanDescriptionType paymentPlanDescription;
    @XmlElement(name = "SurchargeAssessAmount", required = true)
    protected SurchargeAssessAmountType surchargeAssessAmount;
    @XmlElement(name = "DateCreated", required = true)
    protected DateCreatedType dateCreated;
    @XmlElement(name = "UserCreated", required = true)
    protected UserCreatedType userCreated;
    @XmlElement(name = "PaymentPlanCode", required = true)
    protected PaymentPlanCodeType paymentPlanCode;

    /**
     * Gets the value of the policyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyReferenceType }
     *     
     */
    public PolicyReferenceType getPolicyReference() {
        return policyReference;
    }

    /**
     * Sets the value of the policyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyReferenceType }
     *     
     */
    public void setPolicyReference(PolicyReferenceType value) {
        this.policyReference = value;
    }

    /**
     * Gets the value of the installmentId property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentIdType }
     *     
     */
    public InstallmentIdType getInstallmentId() {
        return installmentId;
    }

    /**
     * Sets the value of the installmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentIdType }
     *     
     */
    public void setInstallmentId(InstallmentIdType value) {
        this.installmentId = value;
    }

    /**
     * Gets the value of the displayInstallmentId property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayInstallmentIdType }
     *     
     */
    public DisplayInstallmentIdType getDisplayInstallmentId() {
        return displayInstallmentId;
    }

    /**
     * Sets the value of the displayInstallmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayInstallmentIdType }
     *     
     */
    public void setDisplayInstallmentId(DisplayInstallmentIdType value) {
        this.displayInstallmentId = value;
    }

    /**
     * Gets the value of the paymentPlanId property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentPlanIdType }
     *     
     */
    public PaymentPlanIdType getPaymentPlanId() {
        return paymentPlanId;
    }

    /**
     * Sets the value of the paymentPlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentPlanIdType }
     *     
     */
    public void setPaymentPlanId(PaymentPlanIdType value) {
        this.paymentPlanId = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link DueDateType }
     *     
     */
    public DueDateType getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DueDateType }
     *     
     */
    public void setDueDate(DueDateType value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the sendDate property.
     * 
     * @return
     *     possible object is
     *     {@link SendDateType }
     *     
     */
    public SendDateType getSendDate() {
        return sendDate;
    }

    /**
     * Sets the value of the sendDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendDateType }
     *     
     */
    public void setSendDate(SendDateType value) {
        this.sendDate = value;
    }

    /**
     * Gets the value of the paymentPlanDescription property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentPlanDescriptionType }
     *     
     */
    public PaymentPlanDescriptionType getPaymentPlanDescription() {
        return paymentPlanDescription;
    }

    /**
     * Sets the value of the paymentPlanDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentPlanDescriptionType }
     *     
     */
    public void setPaymentPlanDescription(PaymentPlanDescriptionType value) {
        this.paymentPlanDescription = value;
    }

    /**
     * Gets the value of the surchargeAssessAmount property.
     * 
     * @return
     *     possible object is
     *     {@link SurchargeAssessAmountType }
     *     
     */
    public SurchargeAssessAmountType getSurchargeAssessAmount() {
        return surchargeAssessAmount;
    }

    /**
     * Sets the value of the surchargeAssessAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurchargeAssessAmountType }
     *     
     */
    public void setSurchargeAssessAmount(SurchargeAssessAmountType value) {
        this.surchargeAssessAmount = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link DateCreatedType }
     *     
     */
    public DateCreatedType getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCreatedType }
     *     
     */
    public void setDateCreated(DateCreatedType value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link UserCreatedType }
     *     
     */
    public UserCreatedType getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserCreatedType }
     *     
     */
    public void setUserCreated(UserCreatedType value) {
        this.userCreated = value;
    }

    /**
     * Gets the value of the paymentPlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentPlanCodeType }
     *     
     */
    public PaymentPlanCodeType getPaymentPlanCode() {
        return paymentPlanCode;
    }

    /**
     * Sets the value of the paymentPlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentPlanCodeType }
     *     
     */
    public void setPaymentPlanCode(PaymentPlanCodeType value) {
        this.paymentPlanCode = value;
    }

}
