//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for InsuredType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuredType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusinessName" type="{}BusinessNameType"/>
 *         &lt;element name="CreateShellAccount" type="{}CreateShellAccountType"/>
 *         &lt;element name="CAddr1Type" type="{}CAddr1TypeType"/>
 *         &lt;element name="CAddr2Type" type="{}CAddr2TypeType"/>
 *         &lt;element name="CCompanyType" type="{}CCompanyTypeType"/>
 *         &lt;element name="CCompClassCode" type="{}CCompClassCodeType"/>
 *         &lt;element name="CDateIncorporated" type="{}CDateIncorporatedType"/>
 *         &lt;element name="CFormType" type="{}CFormTypeType"/>
 *         &lt;element name="CFormTypeFlag" type="{}CFormTypeFlagType"/>
 *         &lt;element name="CInsNamOfacCheckTime" type="{}CInsNamOfacCheckTimeType"/>
 *         &lt;element name="CIsoCode" type="{}CIsoCodeType"/>
 *         &lt;element name="CIsoDescription" type="{}CIsoDescriptionType"/>
 *         &lt;element name="CLegalEntityCd" type="{}CLegalEntityCdType"/>
 *         &lt;element name="CNaicDescription" type="{}CNaicDescriptionType"/>
 *         &lt;element name="CNyftz" type="{}CNyftzType"/>
 *         &lt;element name="CNyftzClassCode" type="{}CNyftzClassCodeType"/>
 *         &lt;element name="COfacCheckStatus" type="{}COfacCheckStatusType"/>
 *         &lt;element name="COfacCheckStatusMsg" type="{}COfacCheckStatusMsgType"/>
 *         &lt;element name="COwnership" type="{}COwnershipType"/>
 *         &lt;element name="CPhoneType" type="{}CPhoneTypeType"/>
 *         &lt;element name="CPolicyType" type="{}CPolicyTypeType"/>
 *         &lt;element name="CPolIsoCounter" type="{}CPolIsoCounterType"/>
 *         &lt;element name="CSicDescription" type="{}CSicDescriptionType"/>
 *         &lt;element name="DbNumber" type="{}DbNumberType"/>
 *         &lt;element name="FeinPhoneRequired" type="{}FeinPhoneRequiredType"/>
 *         &lt;element name="IndRiskSituation" type="{}IndRiskSituationType"/>
 *         &lt;element name="InsuredSearchComplete" type="{}InsuredSearchCompleteType"/>
 *         &lt;element name="InsuredType" type="{}InsuredTypeType"/>
 *         &lt;element name="InsuredTypeCode" type="{}InsuredTypeCodeType"/>
 *         &lt;element name="IsDeregulated" type="{}IsDeregulatedType"/>
 *         &lt;element name="MasterRecordGid" type="{}MasterRecordGidType"/>
 *         &lt;element name="NaicsCode" type="{}NaicsCodeType"/>
 *         &lt;element name="NameType" type="{}NameTypeType"/>
 *         &lt;element name="NameTypeStatCode" type="{}NameTypeStatCodeType"/>
 *         &lt;element name="OrderCreditScore" type="{}OrderCreditScoreType"/>
 *         &lt;element name="QuoteNumber" type="{}QuoteNumberType"/>
 *         &lt;element name="RcFailureCancel" type="{}RcFailureCancelType"/>
 *         &lt;element name="RetrieveQuoteNumber" type="{}RetrieveQuoteNumberType"/>
 *         &lt;element name="SicCode" type="{}SicCodeType"/>
 *         &lt;element name="AddressList" type="{}AddressListType"/>
 *         &lt;element name="ContactList" type="{}ContactListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DateModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EntityReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RefName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RefValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="UserModified" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuredType", propOrder = {
    "businessName",
    "createShellAccount",
    "cAddr1Type",
    "cAddr2Type",
    "cCompanyType",
    "cCompClassCode",
    "cDateIncorporated",
    "cFormType",
    "cFormTypeFlag",
    "cInsNamOfacCheckTime",
    "cIsoCode",
    "cIsoDescription",
    "cLegalEntityCd",
    "cNaicDescription",
    "cNyftz",
    "cNyftzClassCode",
    "cOfacCheckStatus",
    "cOfacCheckStatusMsg",
    "cOwnership",
    "cPhoneType",
    "cPolicyType",
    "cPolIsoCounter",
    "cSicDescription",
    "dbNumber",
    "feinPhoneRequired",
    "indRiskSituation",
    "insuredSearchComplete",
    "insuredType",
    "insuredTypeCode",
    "isDeregulated",
    "masterRecordGid",
    "naicsCode",
    "nameType",
    "nameTypeStatCode",
    "orderCreditScore",
    "quoteNumber",
    "rcFailureCancel",
    "retrieveQuoteNumber",
    "sicCode",
    "addressList",
    "contactList"
})
public class InsuredType {

    @XmlElement(name = "BusinessName", required = true)
    protected BusinessNameType businessName;
    @XmlElement(name = "CreateShellAccount", required = true)
    protected CreateShellAccountType createShellAccount;
    @XmlElement(name = "CAddr1Type", required = true)
    protected CAddr1TypeType cAddr1Type;
    @XmlElement(name = "CAddr2Type", required = true)
    protected CAddr2TypeType cAddr2Type;
    @XmlElement(name = "CCompanyType", required = true)
    protected CCompanyTypeType cCompanyType;
    @XmlElement(name = "CCompClassCode", required = true)
    protected CCompClassCodeType cCompClassCode;
    @XmlElement(name = "CDateIncorporated", required = true)
    protected CDateIncorporatedType cDateIncorporated;
    @XmlElement(name = "CFormType", required = true)
    protected CFormTypeType cFormType;
    @XmlElement(name = "CFormTypeFlag", required = true)
    protected CFormTypeFlagType cFormTypeFlag;
    @XmlElement(name = "CInsNamOfacCheckTime", required = true)
    protected CInsNamOfacCheckTimeType cInsNamOfacCheckTime;
    @XmlElement(name = "CIsoCode", required = true)
    protected CIsoCodeType cIsoCode;
    @XmlElement(name = "CIsoDescription", required = true)
    protected CIsoDescriptionType cIsoDescription;
    @XmlElement(name = "CLegalEntityCd", required = true)
    protected CLegalEntityCdType cLegalEntityCd;
    @XmlElement(name = "CNaicDescription", required = true)
    protected CNaicDescriptionType cNaicDescription;
    @XmlElement(name = "CNyftz", required = true)
    protected CNyftzType cNyftz;
    @XmlElement(name = "CNyftzClassCode", required = true)
    protected CNyftzClassCodeType cNyftzClassCode;
    @XmlElement(name = "COfacCheckStatus", required = true)
    protected COfacCheckStatusType cOfacCheckStatus;
    @XmlElement(name = "COfacCheckStatusMsg", required = true)
    protected COfacCheckStatusMsgType cOfacCheckStatusMsg;
    @XmlElement(name = "COwnership", required = true)
    protected COwnershipType cOwnership;
    @XmlElement(name = "CPhoneType", required = true)
    protected CPhoneTypeType cPhoneType;
    @XmlElement(name = "CPolicyType", required = true)
    protected CPolicyTypeType cPolicyType;
    @XmlElement(name = "CPolIsoCounter", required = true)
    protected CPolIsoCounterType cPolIsoCounter;
    @XmlElement(name = "CSicDescription", required = true)
    protected CSicDescriptionType cSicDescription;
    @XmlElement(name = "DbNumber", required = true)
    protected DbNumberType dbNumber;
    @XmlElement(name = "FeinPhoneRequired", required = true)
    protected FeinPhoneRequiredType feinPhoneRequired;
    @XmlElement(name = "IndRiskSituation", required = true)
    protected IndRiskSituationType indRiskSituation;
    @XmlElement(name = "InsuredSearchComplete", required = true)
    protected InsuredSearchCompleteType insuredSearchComplete;
    @XmlElement(name = "InsuredType", required = true)
    protected InsuredTypeType insuredType;
    @XmlElement(name = "InsuredTypeCode", required = true)
    protected InsuredTypeCodeType insuredTypeCode;
    @XmlElement(name = "IsDeregulated", required = true)
    protected IsDeregulatedType isDeregulated;
    @XmlElement(name = "MasterRecordGid", required = true)
    protected MasterRecordGidType masterRecordGid;
    @XmlElement(name = "NaicsCode", required = true)
    protected NaicsCodeType naicsCode;
    @XmlElement(name = "NameType", required = true)
    protected NameTypeType nameType;
    @XmlElement(name = "NameTypeStatCode", required = true)
    protected NameTypeStatCodeType nameTypeStatCode;
    @XmlElement(name = "OrderCreditScore", required = true)
    protected OrderCreditScoreType orderCreditScore;
    @XmlElement(name = "QuoteNumber", required = true)
    protected QuoteNumberType quoteNumber;
    @XmlElement(name = "RcFailureCancel", required = true)
    protected RcFailureCancelType rcFailureCancel;
    @XmlElement(name = "RetrieveQuoteNumber", required = true)
    protected RetrieveQuoteNumberType retrieveQuoteNumber;
    @XmlElement(name = "SicCode", required = true)
    protected SicCodeType sicCode;
    @XmlElement(name = "AddressList", required = true)
    protected AddressListType addressList;
    @XmlElement(name = "ContactList", required = true)
    protected ContactListType contactList;
    @XmlAttribute(name = "DateCreated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlAttribute(name = "DateModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateModified;
    @XmlAttribute(name = "EntityReference")
    protected String entityReference;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "Gid")
    protected Integer gid;
    @XmlAttribute(name = "Id")
    protected Integer id;
    @XmlAttribute(name = "RefName")
    protected String refName;
    @XmlAttribute(name = "RefValue")
    protected Integer refValue;
    @XmlAttribute(name = "UserCreated")
    protected String userCreated;
    @XmlAttribute(name = "UserModified")
    protected String userModified;

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessNameType }
     *     
     */
    public BusinessNameType getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessNameType }
     *     
     */
    public void setBusinessName(BusinessNameType value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the createShellAccount property.
     * 
     * @return
     *     possible object is
     *     {@link CreateShellAccountType }
     *     
     */
    public CreateShellAccountType getCreateShellAccount() {
        return createShellAccount;
    }

    /**
     * Sets the value of the createShellAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateShellAccountType }
     *     
     */
    public void setCreateShellAccount(CreateShellAccountType value) {
        this.createShellAccount = value;
    }

    /**
     * Gets the value of the cAddr1Type property.
     * 
     * @return
     *     possible object is
     *     {@link CAddr1TypeType }
     *     
     */
    public CAddr1TypeType getCAddr1Type() {
        return cAddr1Type;
    }

    /**
     * Sets the value of the cAddr1Type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAddr1TypeType }
     *     
     */
    public void setCAddr1Type(CAddr1TypeType value) {
        this.cAddr1Type = value;
    }

    /**
     * Gets the value of the cAddr2Type property.
     * 
     * @return
     *     possible object is
     *     {@link CAddr2TypeType }
     *     
     */
    public CAddr2TypeType getCAddr2Type() {
        return cAddr2Type;
    }

    /**
     * Sets the value of the cAddr2Type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAddr2TypeType }
     *     
     */
    public void setCAddr2Type(CAddr2TypeType value) {
        this.cAddr2Type = value;
    }

    /**
     * Gets the value of the cCompanyType property.
     * 
     * @return
     *     possible object is
     *     {@link CCompanyTypeType }
     *     
     */
    public CCompanyTypeType getCCompanyType() {
        return cCompanyType;
    }

    /**
     * Sets the value of the cCompanyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCompanyTypeType }
     *     
     */
    public void setCCompanyType(CCompanyTypeType value) {
        this.cCompanyType = value;
    }

    /**
     * Gets the value of the cCompClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link CCompClassCodeType }
     *     
     */
    public CCompClassCodeType getCCompClassCode() {
        return cCompClassCode;
    }

    /**
     * Sets the value of the cCompClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCompClassCodeType }
     *     
     */
    public void setCCompClassCode(CCompClassCodeType value) {
        this.cCompClassCode = value;
    }

    /**
     * Gets the value of the cDateIncorporated property.
     * 
     * @return
     *     possible object is
     *     {@link CDateIncorporatedType }
     *     
     */
    public CDateIncorporatedType getCDateIncorporated() {
        return cDateIncorporated;
    }

    /**
     * Sets the value of the cDateIncorporated property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDateIncorporatedType }
     *     
     */
    public void setCDateIncorporated(CDateIncorporatedType value) {
        this.cDateIncorporated = value;
    }

    /**
     * Gets the value of the cFormType property.
     * 
     * @return
     *     possible object is
     *     {@link CFormTypeType }
     *     
     */
    public CFormTypeType getCFormType() {
        return cFormType;
    }

    /**
     * Sets the value of the cFormType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFormTypeType }
     *     
     */
    public void setCFormType(CFormTypeType value) {
        this.cFormType = value;
    }

    /**
     * Gets the value of the cFormTypeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link CFormTypeFlagType }
     *     
     */
    public CFormTypeFlagType getCFormTypeFlag() {
        return cFormTypeFlag;
    }

    /**
     * Sets the value of the cFormTypeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFormTypeFlagType }
     *     
     */
    public void setCFormTypeFlag(CFormTypeFlagType value) {
        this.cFormTypeFlag = value;
    }

    /**
     * Gets the value of the cInsNamOfacCheckTime property.
     * 
     * @return
     *     possible object is
     *     {@link CInsNamOfacCheckTimeType }
     *     
     */
    public CInsNamOfacCheckTimeType getCInsNamOfacCheckTime() {
        return cInsNamOfacCheckTime;
    }

    /**
     * Sets the value of the cInsNamOfacCheckTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CInsNamOfacCheckTimeType }
     *     
     */
    public void setCInsNamOfacCheckTime(CInsNamOfacCheckTimeType value) {
        this.cInsNamOfacCheckTime = value;
    }

    /**
     * Gets the value of the cIsoCode property.
     * 
     * @return
     *     possible object is
     *     {@link CIsoCodeType }
     *     
     */
    public CIsoCodeType getCIsoCode() {
        return cIsoCode;
    }

    /**
     * Sets the value of the cIsoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIsoCodeType }
     *     
     */
    public void setCIsoCode(CIsoCodeType value) {
        this.cIsoCode = value;
    }

    /**
     * Gets the value of the cIsoDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CIsoDescriptionType }
     *     
     */
    public CIsoDescriptionType getCIsoDescription() {
        return cIsoDescription;
    }

    /**
     * Sets the value of the cIsoDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIsoDescriptionType }
     *     
     */
    public void setCIsoDescription(CIsoDescriptionType value) {
        this.cIsoDescription = value;
    }

    /**
     * Gets the value of the cLegalEntityCd property.
     * 
     * @return
     *     possible object is
     *     {@link CLegalEntityCdType }
     *     
     */
    public CLegalEntityCdType getCLegalEntityCd() {
        return cLegalEntityCd;
    }

    /**
     * Sets the value of the cLegalEntityCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLegalEntityCdType }
     *     
     */
    public void setCLegalEntityCd(CLegalEntityCdType value) {
        this.cLegalEntityCd = value;
    }

    /**
     * Gets the value of the cNaicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CNaicDescriptionType }
     *     
     */
    public CNaicDescriptionType getCNaicDescription() {
        return cNaicDescription;
    }

    /**
     * Sets the value of the cNaicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNaicDescriptionType }
     *     
     */
    public void setCNaicDescription(CNaicDescriptionType value) {
        this.cNaicDescription = value;
    }

    /**
     * Gets the value of the cNyftz property.
     * 
     * @return
     *     possible object is
     *     {@link CNyftzType }
     *     
     */
    public CNyftzType getCNyftz() {
        return cNyftz;
    }

    /**
     * Sets the value of the cNyftz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNyftzType }
     *     
     */
    public void setCNyftz(CNyftzType value) {
        this.cNyftz = value;
    }

    /**
     * Gets the value of the cNyftzClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link CNyftzClassCodeType }
     *     
     */
    public CNyftzClassCodeType getCNyftzClassCode() {
        return cNyftzClassCode;
    }

    /**
     * Sets the value of the cNyftzClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNyftzClassCodeType }
     *     
     */
    public void setCNyftzClassCode(CNyftzClassCodeType value) {
        this.cNyftzClassCode = value;
    }

    /**
     * Gets the value of the cOfacCheckStatus property.
     * 
     * @return
     *     possible object is
     *     {@link COfacCheckStatusType }
     *     
     */
    public COfacCheckStatusType getCOfacCheckStatus() {
        return cOfacCheckStatus;
    }

    /**
     * Sets the value of the cOfacCheckStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link COfacCheckStatusType }
     *     
     */
    public void setCOfacCheckStatus(COfacCheckStatusType value) {
        this.cOfacCheckStatus = value;
    }

    /**
     * Gets the value of the cOfacCheckStatusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link COfacCheckStatusMsgType }
     *     
     */
    public COfacCheckStatusMsgType getCOfacCheckStatusMsg() {
        return cOfacCheckStatusMsg;
    }

    /**
     * Sets the value of the cOfacCheckStatusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link COfacCheckStatusMsgType }
     *     
     */
    public void setCOfacCheckStatusMsg(COfacCheckStatusMsgType value) {
        this.cOfacCheckStatusMsg = value;
    }

    /**
     * Gets the value of the cOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link COwnershipType }
     *     
     */
    public COwnershipType getCOwnership() {
        return cOwnership;
    }

    /**
     * Sets the value of the cOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link COwnershipType }
     *     
     */
    public void setCOwnership(COwnershipType value) {
        this.cOwnership = value;
    }

    /**
     * Gets the value of the cPhoneType property.
     * 
     * @return
     *     possible object is
     *     {@link CPhoneTypeType }
     *     
     */
    public CPhoneTypeType getCPhoneType() {
        return cPhoneType;
    }

    /**
     * Sets the value of the cPhoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPhoneTypeType }
     *     
     */
    public void setCPhoneType(CPhoneTypeType value) {
        this.cPhoneType = value;
    }

    /**
     * Gets the value of the cPolicyType property.
     * 
     * @return
     *     possible object is
     *     {@link CPolicyTypeType }
     *     
     */
    public CPolicyTypeType getCPolicyType() {
        return cPolicyType;
    }

    /**
     * Sets the value of the cPolicyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPolicyTypeType }
     *     
     */
    public void setCPolicyType(CPolicyTypeType value) {
        this.cPolicyType = value;
    }

    /**
     * Gets the value of the cPolIsoCounter property.
     * 
     * @return
     *     possible object is
     *     {@link CPolIsoCounterType }
     *     
     */
    public CPolIsoCounterType getCPolIsoCounter() {
        return cPolIsoCounter;
    }

    /**
     * Sets the value of the cPolIsoCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPolIsoCounterType }
     *     
     */
    public void setCPolIsoCounter(CPolIsoCounterType value) {
        this.cPolIsoCounter = value;
    }

    /**
     * Gets the value of the cSicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CSicDescriptionType }
     *     
     */
    public CSicDescriptionType getCSicDescription() {
        return cSicDescription;
    }

    /**
     * Sets the value of the cSicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSicDescriptionType }
     *     
     */
    public void setCSicDescription(CSicDescriptionType value) {
        this.cSicDescription = value;
    }

    /**
     * Gets the value of the dbNumber property.
     * 
     * @return
     *     possible object is
     *     {@link DbNumberType }
     *     
     */
    public DbNumberType getDbNumber() {
        return dbNumber;
    }

    /**
     * Sets the value of the dbNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbNumberType }
     *     
     */
    public void setDbNumber(DbNumberType value) {
        this.dbNumber = value;
    }

    /**
     * Gets the value of the feinPhoneRequired property.
     * 
     * @return
     *     possible object is
     *     {@link FeinPhoneRequiredType }
     *     
     */
    public FeinPhoneRequiredType getFeinPhoneRequired() {
        return feinPhoneRequired;
    }

    /**
     * Sets the value of the feinPhoneRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeinPhoneRequiredType }
     *     
     */
    public void setFeinPhoneRequired(FeinPhoneRequiredType value) {
        this.feinPhoneRequired = value;
    }

    /**
     * Gets the value of the indRiskSituation property.
     * 
     * @return
     *     possible object is
     *     {@link IndRiskSituationType }
     *     
     */
    public IndRiskSituationType getIndRiskSituation() {
        return indRiskSituation;
    }

    /**
     * Sets the value of the indRiskSituation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndRiskSituationType }
     *     
     */
    public void setIndRiskSituation(IndRiskSituationType value) {
        this.indRiskSituation = value;
    }

    /**
     * Gets the value of the insuredSearchComplete property.
     * 
     * @return
     *     possible object is
     *     {@link InsuredSearchCompleteType }
     *     
     */
    public InsuredSearchCompleteType getInsuredSearchComplete() {
        return insuredSearchComplete;
    }

    /**
     * Sets the value of the insuredSearchComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuredSearchCompleteType }
     *     
     */
    public void setInsuredSearchComplete(InsuredSearchCompleteType value) {
        this.insuredSearchComplete = value;
    }

    /**
     * Gets the value of the insuredType property.
     * 
     * @return
     *     possible object is
     *     {@link InsuredTypeType }
     *     
     */
    public InsuredTypeType getInsuredType() {
        return insuredType;
    }

    /**
     * Sets the value of the insuredType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuredTypeType }
     *     
     */
    public void setInsuredType(InsuredTypeType value) {
        this.insuredType = value;
    }

    /**
     * Gets the value of the insuredTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link InsuredTypeCodeType }
     *     
     */
    public InsuredTypeCodeType getInsuredTypeCode() {
        return insuredTypeCode;
    }

    /**
     * Sets the value of the insuredTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuredTypeCodeType }
     *     
     */
    public void setInsuredTypeCode(InsuredTypeCodeType value) {
        this.insuredTypeCode = value;
    }

    /**
     * Gets the value of the isDeregulated property.
     * 
     * @return
     *     possible object is
     *     {@link IsDeregulatedType }
     *     
     */
    public IsDeregulatedType getIsDeregulated() {
        return isDeregulated;
    }

    /**
     * Sets the value of the isDeregulated property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsDeregulatedType }
     *     
     */
    public void setIsDeregulated(IsDeregulatedType value) {
        this.isDeregulated = value;
    }

    /**
     * Gets the value of the masterRecordGid property.
     * 
     * @return
     *     possible object is
     *     {@link MasterRecordGidType }
     *     
     */
    public MasterRecordGidType getMasterRecordGid() {
        return masterRecordGid;
    }

    /**
     * Sets the value of the masterRecordGid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterRecordGidType }
     *     
     */
    public void setMasterRecordGid(MasterRecordGidType value) {
        this.masterRecordGid = value;
    }

    /**
     * Gets the value of the naicsCode property.
     * 
     * @return
     *     possible object is
     *     {@link NaicsCodeType }
     *     
     */
    public NaicsCodeType getNaicsCode() {
        return naicsCode;
    }

    /**
     * Sets the value of the naicsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaicsCodeType }
     *     
     */
    public void setNaicsCode(NaicsCodeType value) {
        this.naicsCode = value;
    }

    /**
     * Gets the value of the nameType property.
     * 
     * @return
     *     possible object is
     *     {@link NameTypeType }
     *     
     */
    public NameTypeType getNameType() {
        return nameType;
    }

    /**
     * Sets the value of the nameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameTypeType }
     *     
     */
    public void setNameType(NameTypeType value) {
        this.nameType = value;
    }

    /**
     * Gets the value of the nameTypeStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link NameTypeStatCodeType }
     *     
     */
    public NameTypeStatCodeType getNameTypeStatCode() {
        return nameTypeStatCode;
    }

    /**
     * Sets the value of the nameTypeStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameTypeStatCodeType }
     *     
     */
    public void setNameTypeStatCode(NameTypeStatCodeType value) {
        this.nameTypeStatCode = value;
    }

    /**
     * Gets the value of the orderCreditScore property.
     * 
     * @return
     *     possible object is
     *     {@link OrderCreditScoreType }
     *     
     */
    public OrderCreditScoreType getOrderCreditScore() {
        return orderCreditScore;
    }

    /**
     * Sets the value of the orderCreditScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderCreditScoreType }
     *     
     */
    public void setOrderCreditScore(OrderCreditScoreType value) {
        this.orderCreditScore = value;
    }

    /**
     * Gets the value of the quoteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteNumberType }
     *     
     */
    public QuoteNumberType getQuoteNumber() {
        return quoteNumber;
    }

    /**
     * Sets the value of the quoteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteNumberType }
     *     
     */
    public void setQuoteNumber(QuoteNumberType value) {
        this.quoteNumber = value;
    }

    /**
     * Gets the value of the rcFailureCancel property.
     * 
     * @return
     *     possible object is
     *     {@link RcFailureCancelType }
     *     
     */
    public RcFailureCancelType getRcFailureCancel() {
        return rcFailureCancel;
    }

    /**
     * Sets the value of the rcFailureCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RcFailureCancelType }
     *     
     */
    public void setRcFailureCancel(RcFailureCancelType value) {
        this.rcFailureCancel = value;
    }

    /**
     * Gets the value of the retrieveQuoteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link RetrieveQuoteNumberType }
     *     
     */
    public RetrieveQuoteNumberType getRetrieveQuoteNumber() {
        return retrieveQuoteNumber;
    }

    /**
     * Sets the value of the retrieveQuoteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrieveQuoteNumberType }
     *     
     */
    public void setRetrieveQuoteNumber(RetrieveQuoteNumberType value) {
        this.retrieveQuoteNumber = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link SicCodeType }
     *     
     */
    public SicCodeType getSicCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SicCodeType }
     *     
     */
    public void setSicCode(SicCodeType value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the addressList property.
     * 
     * @return
     *     possible object is
     *     {@link AddressListType }
     *     
     */
    public AddressListType getAddressList() {
        return addressList;
    }

    /**
     * Sets the value of the addressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressListType }
     *     
     */
    public void setAddressList(AddressListType value) {
        this.addressList = value;
    }

    /**
     * Gets the value of the contactList property.
     * 
     * @return
     *     possible object is
     *     {@link ContactListType }
     *     
     */
    public ContactListType getContactList() {
        return contactList;
    }

    /**
     * Sets the value of the contactList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactListType }
     *     
     */
    public void setContactList(ContactListType value) {
        this.contactList = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateModified(XMLGregorianCalendar value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the entityReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityReference() {
        return entityReference;
    }

    /**
     * Sets the value of the entityReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityReference(String value) {
        this.entityReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGid(Integer value) {
        this.gid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the refValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefValue() {
        return refValue;
    }

    /**
     * Sets the value of the refValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefValue(Integer value) {
        this.refValue = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

    /**
     * Gets the value of the userModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserModified() {
        return userModified;
    }

    /**
     * Sets the value of the userModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserModified(String value) {
        this.userModified = value;
    }

}
