//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 12:22:48 PM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MDExposureInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MDExposureInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CExposureInfo" type="{}CExposureInfoType"/>
 *         &lt;element name="CGenInfoRevenue" type="{}CGenInfoRevenueType"/>
 *         &lt;element name="COccurrOrClaimsMade" type="{}COccurrOrClaimsMadeType"/>
 *         &lt;element name="CResetDefaultsOnDate" type="{}CResetDefaultsOnDateType"/>
 *         &lt;element name="CRevenue" type="{}CRevenueType"/>
 *         &lt;element name="CScheduledMedia" type="{}CScheduledMediaType"/>
 *         &lt;element name="CTypeOfMedia" type="{}CTypeOfMediaType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EntityReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RefName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RefValue" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MDExposureInformationType", propOrder = {
    "cExposureInfo",
    "cGenInfoRevenue",
    "cOccurrOrClaimsMade",
    "cResetDefaultsOnDate",
    "cRevenue",
    "cScheduledMedia",
    "cTypeOfMedia"
})
public class MDExposureInformationType {

    @XmlElement(name = "CExposureInfo", required = true)
    protected CExposureInfoType cExposureInfo;
    @XmlElement(name = "CGenInfoRevenue", required = true)
    protected CGenInfoRevenueType cGenInfoRevenue;
    @XmlElement(name = "COccurrOrClaimsMade", required = true)
    protected COccurrOrClaimsMadeType cOccurrOrClaimsMade;
    @XmlElement(name = "CResetDefaultsOnDate", required = true)
    protected CResetDefaultsOnDateType cResetDefaultsOnDate;
    @XmlElement(name = "CRevenue", required = true)
    protected CRevenueType cRevenue;
    @XmlElement(name = "CScheduledMedia", required = true)
    protected CScheduledMediaType cScheduledMedia;
    @XmlElement(name = "CTypeOfMedia", required = true)
    protected CTypeOfMediaType cTypeOfMedia;
    @XmlAttribute(name = "DateCreated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlAttribute(name = "EntityReference")
    protected String entityReference;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "Gid")
    protected Integer gid;
    @XmlAttribute(name = "Id")
    protected Integer id;
    @XmlAttribute(name = "RefName")
    protected String refName;
    @XmlAttribute(name = "RefValue")
    protected Short refValue;
    @XmlAttribute(name = "UserCreated")
    protected String userCreated;

    /**
     * Gets the value of the cExposureInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CExposureInfoType }
     *     
     */
    public CExposureInfoType getCExposureInfo() {
        return cExposureInfo;
    }

    /**
     * Sets the value of the cExposureInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CExposureInfoType }
     *     
     */
    public void setCExposureInfo(CExposureInfoType value) {
        this.cExposureInfo = value;
    }

    /**
     * Gets the value of the cGenInfoRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link CGenInfoRevenueType }
     *     
     */
    public CGenInfoRevenueType getCGenInfoRevenue() {
        return cGenInfoRevenue;
    }

    /**
     * Sets the value of the cGenInfoRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGenInfoRevenueType }
     *     
     */
    public void setCGenInfoRevenue(CGenInfoRevenueType value) {
        this.cGenInfoRevenue = value;
    }

    /**
     * Gets the value of the cOccurrOrClaimsMade property.
     * 
     * @return
     *     possible object is
     *     {@link COccurrOrClaimsMadeType }
     *     
     */
    public COccurrOrClaimsMadeType getCOccurrOrClaimsMade() {
        return cOccurrOrClaimsMade;
    }

    /**
     * Sets the value of the cOccurrOrClaimsMade property.
     * 
     * @param value
     *     allowed object is
     *     {@link COccurrOrClaimsMadeType }
     *     
     */
    public void setCOccurrOrClaimsMade(COccurrOrClaimsMadeType value) {
        this.cOccurrOrClaimsMade = value;
    }

    /**
     * Gets the value of the cResetDefaultsOnDate property.
     * 
     * @return
     *     possible object is
     *     {@link CResetDefaultsOnDateType }
     *     
     */
    public CResetDefaultsOnDateType getCResetDefaultsOnDate() {
        return cResetDefaultsOnDate;
    }

    /**
     * Sets the value of the cResetDefaultsOnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CResetDefaultsOnDateType }
     *     
     */
    public void setCResetDefaultsOnDate(CResetDefaultsOnDateType value) {
        this.cResetDefaultsOnDate = value;
    }

    /**
     * Gets the value of the cRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link CRevenueType }
     *     
     */
    public CRevenueType getCRevenue() {
        return cRevenue;
    }

    /**
     * Sets the value of the cRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRevenueType }
     *     
     */
    public void setCRevenue(CRevenueType value) {
        this.cRevenue = value;
    }

    /**
     * Gets the value of the cScheduledMedia property.
     * 
     * @return
     *     possible object is
     *     {@link CScheduledMediaType }
     *     
     */
    public CScheduledMediaType getCScheduledMedia() {
        return cScheduledMedia;
    }

    /**
     * Sets the value of the cScheduledMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CScheduledMediaType }
     *     
     */
    public void setCScheduledMedia(CScheduledMediaType value) {
        this.cScheduledMedia = value;
    }

    /**
     * Gets the value of the cTypeOfMedia property.
     * 
     * @return
     *     possible object is
     *     {@link CTypeOfMediaType }
     *     
     */
    public CTypeOfMediaType getCTypeOfMedia() {
        return cTypeOfMedia;
    }

    /**
     * Sets the value of the cTypeOfMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTypeOfMediaType }
     *     
     */
    public void setCTypeOfMedia(CTypeOfMediaType value) {
        this.cTypeOfMedia = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the entityReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityReference() {
        return entityReference;
    }

    /**
     * Sets the value of the entityReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityReference(String value) {
        this.entityReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGid(Integer value) {
        this.gid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the refValue property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRefValue() {
        return refValue;
    }

    /**
     * Sets the value of the refValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRefValue(Short value) {
        this.refValue = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

}
