//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 12:22:48 PM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MDPremiumSummaryDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MDPremiumSummaryDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnnualPremium" type="{}AnnualPremiumType"/>
 *         &lt;element name="BalanceToMinimum" type="{}BalanceToMinimumType"/>
 *         &lt;element name="CommissionablePremium" type="{}CommissionablePremiumType"/>
 *         &lt;element name="CAslob" type="{}CAslobType"/>
 *         &lt;element name="CCoverage" type="{}CCoverageType"/>
 *         &lt;element name="CCoverageCode" type="{}CCoverageCodeType"/>
 *         &lt;element name="CCoveragePartCode" type="{}CCoveragePartCodeType"/>
 *         &lt;element name="CCoveragePartName" type="{}CCoveragePartNameType"/>
 *         &lt;element name="CCoverageTypeCode" type="{}CCoverageTypeCodeType"/>
 *         &lt;element name="CCoverageTypeName" type="{}CCoverageTypeNameType"/>
 *         &lt;element name="CDes" type="{}CDesType"/>
 *         &lt;element name="CDevFrmSchdledExcess" type="{}CDevFrmSchdledExcessType"/>
 *         &lt;element name="CDevFrmSchdledPrimary" type="{}CDevFrmSchdledPrimaryType"/>
 *         &lt;element name="CDevFrmSchPrimDisp" type="{}CDevFrmSchPrimDispType"/>
 *         &lt;element name="CFinalPremium" type="{}CFinalPremiumType"/>
 *         &lt;element name="CFinalPremDisp" type="{}CFinalPremDispType"/>
 *         &lt;element name="CFullyEarned" type="{}CFullyEarnedType"/>
 *         &lt;element name="CFullyEarnedOverride" type="{}CFullyEarnedOverrideType"/>
 *         &lt;element name="CLobDescription" type="{}CLobDescriptionType"/>
 *         &lt;element name="CManualPrem" type="{}CManualPremType"/>
 *         &lt;element name="CManualPremDisp" type="{}CManualPremDispType"/>
 *         &lt;element name="CPrsDetailTwisty" type="{}CPrsDetailTwistyType"/>
 *         &lt;element name="CPublicQbeEquPrem" type="{}CPublicQbeEquPremType"/>
 *         &lt;element name="CPubQbeEquPremDisp" type="{}CPubQbeEquPremDispType"/>
 *         &lt;element name="CRatedPrem" type="{}CRatedPremType"/>
 *         &lt;element name="CRatedPremDisp" type="{}CRatedPremDispType"/>
 *         &lt;element name="CRatingFormula" type="{}CRatingFormulaType"/>
 *         &lt;element name="CRatingFunction" type="{}CRatingFunctionType"/>
 *         &lt;element name="CSeq" type="{}CSeqType"/>
 *         &lt;element name="CSubLineCode" type="{}CSubLineCodeType"/>
 *         &lt;element name="FullTermPremium" type="{}FullTermPremiumType"/>
 *         &lt;element name="IsCovManuallyRated" type="{}IsCovManuallyRatedType"/>
 *         &lt;element name="IsSubToFullyCharge" type="{}IsSubToFullyChargeType"/>
 *         &lt;element name="IsSubToFullyEarn" type="{}IsSubToFullyEarnType"/>
 *         &lt;element name="LobCode" type="{}LobCodeType"/>
 *         &lt;element name="ProductCode" type="{}ProductCodeType"/>
 *         &lt;element name="RiskState" type="{}RiskStateType"/>
 *         &lt;element name="RiskStateStatCode" type="{}RiskStateStatCodeType"/>
 *         &lt;element name="TransactionPremium" type="{}TransactionPremiumType"/>
 *         &lt;element name="TransPremNotSubToAud" type="{}TransPremNotSubToAudType"/>
 *         &lt;element name="WaivedPremium" type="{}WaivedPremiumType"/>
 *         &lt;element name="WrittenPremium" type="{}WrittenPremiumType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EntityReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RefName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RefValue" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MDPremiumSummaryDetailType", propOrder = {
    "annualPremium",
    "balanceToMinimum",
    "commissionablePremium",
    "cAslob",
    "cCoverage",
    "cCoverageCode",
    "cCoveragePartCode",
    "cCoveragePartName",
    "cCoverageTypeCode",
    "cCoverageTypeName",
    "cDes",
    "cDevFrmSchdledExcess",
    "cDevFrmSchdledPrimary",
    "cDevFrmSchPrimDisp",
    "cFinalPremium",
    "cFinalPremDisp",
    "cFullyEarned",
    "cFullyEarnedOverride",
    "cLobDescription",
    "cManualPrem",
    "cManualPremDisp",
    "cPrsDetailTwisty",
    "cPublicQbeEquPrem",
    "cPubQbeEquPremDisp",
    "cRatedPrem",
    "cRatedPremDisp",
    "cRatingFormula",
    "cRatingFunction",
    "cSeq",
    "cSubLineCode",
    "fullTermPremium",
    "isCovManuallyRated",
    "isSubToFullyCharge",
    "isSubToFullyEarn",
    "lobCode",
    "productCode",
    "riskState",
    "riskStateStatCode",
    "transactionPremium",
    "transPremNotSubToAud",
    "waivedPremium",
    "writtenPremium"
})
public class MDPremiumSummaryDetailType {

    @XmlElement(name = "AnnualPremium", required = true)
    protected AnnualPremiumType annualPremium;
    @XmlElement(name = "BalanceToMinimum", required = true)
    protected BalanceToMinimumType balanceToMinimum;
    @XmlElement(name = "CommissionablePremium", required = true)
    protected CommissionablePremiumType commissionablePremium;
    @XmlElement(name = "CAslob", required = true)
    protected CAslobType cAslob;
    @XmlElement(name = "CCoverage", required = true)
    protected CCoverageType cCoverage;
    @XmlElement(name = "CCoverageCode", required = true)
    protected CCoverageCodeType cCoverageCode;
    @XmlElement(name = "CCoveragePartCode", required = true)
    protected CCoveragePartCodeType cCoveragePartCode;
    @XmlElement(name = "CCoveragePartName", required = true)
    protected CCoveragePartNameType cCoveragePartName;
    @XmlElement(name = "CCoverageTypeCode", required = true)
    protected CCoverageTypeCodeType cCoverageTypeCode;
    @XmlElement(name = "CCoverageTypeName", required = true)
    protected CCoverageTypeNameType cCoverageTypeName;
    @XmlElement(name = "CDes", required = true)
    protected CDesType cDes;
    @XmlElement(name = "CDevFrmSchdledExcess", required = true)
    protected CDevFrmSchdledExcessType cDevFrmSchdledExcess;
    @XmlElement(name = "CDevFrmSchdledPrimary", required = true)
    protected CDevFrmSchdledPrimaryType cDevFrmSchdledPrimary;
    @XmlElement(name = "CDevFrmSchPrimDisp", required = true)
    protected CDevFrmSchPrimDispType cDevFrmSchPrimDisp;
    @XmlElement(name = "CFinalPremium", required = true)
    protected CFinalPremiumType cFinalPremium;
    @XmlElement(name = "CFinalPremDisp", required = true)
    protected CFinalPremDispType cFinalPremDisp;
    @XmlElement(name = "CFullyEarned", required = true)
    protected CFullyEarnedType cFullyEarned;
    @XmlElement(name = "CFullyEarnedOverride", required = true)
    protected CFullyEarnedOverrideType cFullyEarnedOverride;
    @XmlElement(name = "CLobDescription", required = true)
    protected CLobDescriptionType cLobDescription;
    @XmlElement(name = "CManualPrem", required = true)
    protected CManualPremType cManualPrem;
    @XmlElement(name = "CManualPremDisp", required = true)
    protected CManualPremDispType cManualPremDisp;
    @XmlElement(name = "CPrsDetailTwisty", required = true)
    protected CPrsDetailTwistyType cPrsDetailTwisty;
    @XmlElement(name = "CPublicQbeEquPrem", required = true)
    protected CPublicQbeEquPremType cPublicQbeEquPrem;
    @XmlElement(name = "CPubQbeEquPremDisp", required = true)
    protected CPubQbeEquPremDispType cPubQbeEquPremDisp;
    @XmlElement(name = "CRatedPrem", required = true)
    protected CRatedPremType cRatedPrem;
    @XmlElement(name = "CRatedPremDisp", required = true)
    protected CRatedPremDispType cRatedPremDisp;
    @XmlElement(name = "CRatingFormula", required = true)
    protected CRatingFormulaType cRatingFormula;
    @XmlElement(name = "CRatingFunction", required = true)
    protected CRatingFunctionType cRatingFunction;
    @XmlElement(name = "CSeq", required = true)
    protected CSeqType cSeq;
    @XmlElement(name = "CSubLineCode", required = true)
    protected CSubLineCodeType cSubLineCode;
    @XmlElement(name = "FullTermPremium", required = true)
    protected FullTermPremiumType fullTermPremium;
    @XmlElement(name = "IsCovManuallyRated", required = true)
    protected IsCovManuallyRatedType isCovManuallyRated;
    @XmlElement(name = "IsSubToFullyCharge", required = true)
    protected IsSubToFullyChargeType isSubToFullyCharge;
    @XmlElement(name = "IsSubToFullyEarn", required = true)
    protected IsSubToFullyEarnType isSubToFullyEarn;
    @XmlElement(name = "LobCode", required = true)
    protected LobCodeType lobCode;
    @XmlElement(name = "ProductCode", required = true)
    protected ProductCodeType productCode;
    @XmlElement(name = "RiskState", required = true)
    protected RiskStateType riskState;
    @XmlElement(name = "RiskStateStatCode", required = true)
    protected RiskStateStatCodeType riskStateStatCode;
    @XmlElement(name = "TransactionPremium", required = true)
    protected TransactionPremiumType transactionPremium;
    @XmlElement(name = "TransPremNotSubToAud", required = true)
    protected TransPremNotSubToAudType transPremNotSubToAud;
    @XmlElement(name = "WaivedPremium", required = true)
    protected WaivedPremiumType waivedPremium;
    @XmlElement(name = "WrittenPremium", required = true)
    protected WrittenPremiumType writtenPremium;
    @XmlAttribute(name = "DateCreated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlAttribute(name = "EntityReference")
    protected String entityReference;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "Gid")
    protected Integer gid;
    @XmlAttribute(name = "Id")
    protected Integer id;
    @XmlAttribute(name = "RefName")
    protected String refName;
    @XmlAttribute(name = "RefValue")
    protected Short refValue;
    @XmlAttribute(name = "UserCreated")
    protected String userCreated;

    /**
     * Gets the value of the annualPremium property.
     * 
     * @return
     *     possible object is
     *     {@link AnnualPremiumType }
     *     
     */
    public AnnualPremiumType getAnnualPremium() {
        return annualPremium;
    }

    /**
     * Sets the value of the annualPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnualPremiumType }
     *     
     */
    public void setAnnualPremium(AnnualPremiumType value) {
        this.annualPremium = value;
    }

    /**
     * Gets the value of the balanceToMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceToMinimumType }
     *     
     */
    public BalanceToMinimumType getBalanceToMinimum() {
        return balanceToMinimum;
    }

    /**
     * Sets the value of the balanceToMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceToMinimumType }
     *     
     */
    public void setBalanceToMinimum(BalanceToMinimumType value) {
        this.balanceToMinimum = value;
    }

    /**
     * Gets the value of the commissionablePremium property.
     * 
     * @return
     *     possible object is
     *     {@link CommissionablePremiumType }
     *     
     */
    public CommissionablePremiumType getCommissionablePremium() {
        return commissionablePremium;
    }

    /**
     * Sets the value of the commissionablePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommissionablePremiumType }
     *     
     */
    public void setCommissionablePremium(CommissionablePremiumType value) {
        this.commissionablePremium = value;
    }

    /**
     * Gets the value of the cAslob property.
     * 
     * @return
     *     possible object is
     *     {@link CAslobType }
     *     
     */
    public CAslobType getCAslob() {
        return cAslob;
    }

    /**
     * Sets the value of the cAslob property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAslobType }
     *     
     */
    public void setCAslob(CAslobType value) {
        this.cAslob = value;
    }

    /**
     * Gets the value of the cCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link CCoverageType }
     *     
     */
    public CCoverageType getCCoverage() {
        return cCoverage;
    }

    /**
     * Sets the value of the cCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoverageType }
     *     
     */
    public void setCCoverage(CCoverageType value) {
        this.cCoverage = value;
    }

    /**
     * Gets the value of the cCoverageCode property.
     * 
     * @return
     *     possible object is
     *     {@link CCoverageCodeType }
     *     
     */
    public CCoverageCodeType getCCoverageCode() {
        return cCoverageCode;
    }

    /**
     * Sets the value of the cCoverageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoverageCodeType }
     *     
     */
    public void setCCoverageCode(CCoverageCodeType value) {
        this.cCoverageCode = value;
    }

    /**
     * Gets the value of the cCoveragePartCode property.
     * 
     * @return
     *     possible object is
     *     {@link CCoveragePartCodeType }
     *     
     */
    public CCoveragePartCodeType getCCoveragePartCode() {
        return cCoveragePartCode;
    }

    /**
     * Sets the value of the cCoveragePartCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoveragePartCodeType }
     *     
     */
    public void setCCoveragePartCode(CCoveragePartCodeType value) {
        this.cCoveragePartCode = value;
    }

    /**
     * Gets the value of the cCoveragePartName property.
     * 
     * @return
     *     possible object is
     *     {@link CCoveragePartNameType }
     *     
     */
    public CCoveragePartNameType getCCoveragePartName() {
        return cCoveragePartName;
    }

    /**
     * Sets the value of the cCoveragePartName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoveragePartNameType }
     *     
     */
    public void setCCoveragePartName(CCoveragePartNameType value) {
        this.cCoveragePartName = value;
    }

    /**
     * Gets the value of the cCoverageTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CCoverageTypeCodeType }
     *     
     */
    public CCoverageTypeCodeType getCCoverageTypeCode() {
        return cCoverageTypeCode;
    }

    /**
     * Sets the value of the cCoverageTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoverageTypeCodeType }
     *     
     */
    public void setCCoverageTypeCode(CCoverageTypeCodeType value) {
        this.cCoverageTypeCode = value;
    }

    /**
     * Gets the value of the cCoverageTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link CCoverageTypeNameType }
     *     
     */
    public CCoverageTypeNameType getCCoverageTypeName() {
        return cCoverageTypeName;
    }

    /**
     * Sets the value of the cCoverageTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCoverageTypeNameType }
     *     
     */
    public void setCCoverageTypeName(CCoverageTypeNameType value) {
        this.cCoverageTypeName = value;
    }

    /**
     * Gets the value of the cDes property.
     * 
     * @return
     *     possible object is
     *     {@link CDesType }
     *     
     */
    public CDesType getCDes() {
        return cDes;
    }

    /**
     * Sets the value of the cDes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDesType }
     *     
     */
    public void setCDes(CDesType value) {
        this.cDes = value;
    }

    /**
     * Gets the value of the cDevFrmSchdledExcess property.
     * 
     * @return
     *     possible object is
     *     {@link CDevFrmSchdledExcessType }
     *     
     */
    public CDevFrmSchdledExcessType getCDevFrmSchdledExcess() {
        return cDevFrmSchdledExcess;
    }

    /**
     * Sets the value of the cDevFrmSchdledExcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDevFrmSchdledExcessType }
     *     
     */
    public void setCDevFrmSchdledExcess(CDevFrmSchdledExcessType value) {
        this.cDevFrmSchdledExcess = value;
    }

    /**
     * Gets the value of the cDevFrmSchdledPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link CDevFrmSchdledPrimaryType }
     *     
     */
    public CDevFrmSchdledPrimaryType getCDevFrmSchdledPrimary() {
        return cDevFrmSchdledPrimary;
    }

    /**
     * Sets the value of the cDevFrmSchdledPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDevFrmSchdledPrimaryType }
     *     
     */
    public void setCDevFrmSchdledPrimary(CDevFrmSchdledPrimaryType value) {
        this.cDevFrmSchdledPrimary = value;
    }

    /**
     * Gets the value of the cDevFrmSchPrimDisp property.
     * 
     * @return
     *     possible object is
     *     {@link CDevFrmSchPrimDispType }
     *     
     */
    public CDevFrmSchPrimDispType getCDevFrmSchPrimDisp() {
        return cDevFrmSchPrimDisp;
    }

    /**
     * Sets the value of the cDevFrmSchPrimDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDevFrmSchPrimDispType }
     *     
     */
    public void setCDevFrmSchPrimDisp(CDevFrmSchPrimDispType value) {
        this.cDevFrmSchPrimDisp = value;
    }

    /**
     * Gets the value of the cFinalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link CFinalPremiumType }
     *     
     */
    public CFinalPremiumType getCFinalPremium() {
        return cFinalPremium;
    }

    /**
     * Sets the value of the cFinalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFinalPremiumType }
     *     
     */
    public void setCFinalPremium(CFinalPremiumType value) {
        this.cFinalPremium = value;
    }

    /**
     * Gets the value of the cFinalPremDisp property.
     * 
     * @return
     *     possible object is
     *     {@link CFinalPremDispType }
     *     
     */
    public CFinalPremDispType getCFinalPremDisp() {
        return cFinalPremDisp;
    }

    /**
     * Sets the value of the cFinalPremDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFinalPremDispType }
     *     
     */
    public void setCFinalPremDisp(CFinalPremDispType value) {
        this.cFinalPremDisp = value;
    }

    /**
     * Gets the value of the cFullyEarned property.
     * 
     * @return
     *     possible object is
     *     {@link CFullyEarnedType }
     *     
     */
    public CFullyEarnedType getCFullyEarned() {
        return cFullyEarned;
    }

    /**
     * Sets the value of the cFullyEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFullyEarnedType }
     *     
     */
    public void setCFullyEarned(CFullyEarnedType value) {
        this.cFullyEarned = value;
    }

    /**
     * Gets the value of the cFullyEarnedOverride property.
     * 
     * @return
     *     possible object is
     *     {@link CFullyEarnedOverrideType }
     *     
     */
    public CFullyEarnedOverrideType getCFullyEarnedOverride() {
        return cFullyEarnedOverride;
    }

    /**
     * Sets the value of the cFullyEarnedOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFullyEarnedOverrideType }
     *     
     */
    public void setCFullyEarnedOverride(CFullyEarnedOverrideType value) {
        this.cFullyEarnedOverride = value;
    }

    /**
     * Gets the value of the cLobDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CLobDescriptionType }
     *     
     */
    public CLobDescriptionType getCLobDescription() {
        return cLobDescription;
    }

    /**
     * Sets the value of the cLobDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLobDescriptionType }
     *     
     */
    public void setCLobDescription(CLobDescriptionType value) {
        this.cLobDescription = value;
    }

    /**
     * Gets the value of the cManualPrem property.
     * 
     * @return
     *     possible object is
     *     {@link CManualPremType }
     *     
     */
    public CManualPremType getCManualPrem() {
        return cManualPrem;
    }

    /**
     * Sets the value of the cManualPrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CManualPremType }
     *     
     */
    public void setCManualPrem(CManualPremType value) {
        this.cManualPrem = value;
    }

    /**
     * Gets the value of the cManualPremDisp property.
     * 
     * @return
     *     possible object is
     *     {@link CManualPremDispType }
     *     
     */
    public CManualPremDispType getCManualPremDisp() {
        return cManualPremDisp;
    }

    /**
     * Sets the value of the cManualPremDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CManualPremDispType }
     *     
     */
    public void setCManualPremDisp(CManualPremDispType value) {
        this.cManualPremDisp = value;
    }

    /**
     * Gets the value of the cPrsDetailTwisty property.
     * 
     * @return
     *     possible object is
     *     {@link CPrsDetailTwistyType }
     *     
     */
    public CPrsDetailTwistyType getCPrsDetailTwisty() {
        return cPrsDetailTwisty;
    }

    /**
     * Sets the value of the cPrsDetailTwisty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPrsDetailTwistyType }
     *     
     */
    public void setCPrsDetailTwisty(CPrsDetailTwistyType value) {
        this.cPrsDetailTwisty = value;
    }

    /**
     * Gets the value of the cPublicQbeEquPrem property.
     * 
     * @return
     *     possible object is
     *     {@link CPublicQbeEquPremType }
     *     
     */
    public CPublicQbeEquPremType getCPublicQbeEquPrem() {
        return cPublicQbeEquPrem;
    }

    /**
     * Sets the value of the cPublicQbeEquPrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPublicQbeEquPremType }
     *     
     */
    public void setCPublicQbeEquPrem(CPublicQbeEquPremType value) {
        this.cPublicQbeEquPrem = value;
    }

    /**
     * Gets the value of the cPubQbeEquPremDisp property.
     * 
     * @return
     *     possible object is
     *     {@link CPubQbeEquPremDispType }
     *     
     */
    public CPubQbeEquPremDispType getCPubQbeEquPremDisp() {
        return cPubQbeEquPremDisp;
    }

    /**
     * Sets the value of the cPubQbeEquPremDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPubQbeEquPremDispType }
     *     
     */
    public void setCPubQbeEquPremDisp(CPubQbeEquPremDispType value) {
        this.cPubQbeEquPremDisp = value;
    }

    /**
     * Gets the value of the cRatedPrem property.
     * 
     * @return
     *     possible object is
     *     {@link CRatedPremType }
     *     
     */
    public CRatedPremType getCRatedPrem() {
        return cRatedPrem;
    }

    /**
     * Sets the value of the cRatedPrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRatedPremType }
     *     
     */
    public void setCRatedPrem(CRatedPremType value) {
        this.cRatedPrem = value;
    }

    /**
     * Gets the value of the cRatedPremDisp property.
     * 
     * @return
     *     possible object is
     *     {@link CRatedPremDispType }
     *     
     */
    public CRatedPremDispType getCRatedPremDisp() {
        return cRatedPremDisp;
    }

    /**
     * Sets the value of the cRatedPremDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRatedPremDispType }
     *     
     */
    public void setCRatedPremDisp(CRatedPremDispType value) {
        this.cRatedPremDisp = value;
    }

    /**
     * Gets the value of the cRatingFormula property.
     * 
     * @return
     *     possible object is
     *     {@link CRatingFormulaType }
     *     
     */
    public CRatingFormulaType getCRatingFormula() {
        return cRatingFormula;
    }

    /**
     * Sets the value of the cRatingFormula property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRatingFormulaType }
     *     
     */
    public void setCRatingFormula(CRatingFormulaType value) {
        this.cRatingFormula = value;
    }

    /**
     * Gets the value of the cRatingFunction property.
     * 
     * @return
     *     possible object is
     *     {@link CRatingFunctionType }
     *     
     */
    public CRatingFunctionType getCRatingFunction() {
        return cRatingFunction;
    }

    /**
     * Sets the value of the cRatingFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRatingFunctionType }
     *     
     */
    public void setCRatingFunction(CRatingFunctionType value) {
        this.cRatingFunction = value;
    }

    /**
     * Gets the value of the cSeq property.
     * 
     * @return
     *     possible object is
     *     {@link CSeqType }
     *     
     */
    public CSeqType getCSeq() {
        return cSeq;
    }

    /**
     * Sets the value of the cSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSeqType }
     *     
     */
    public void setCSeq(CSeqType value) {
        this.cSeq = value;
    }

    /**
     * Gets the value of the cSubLineCode property.
     * 
     * @return
     *     possible object is
     *     {@link CSubLineCodeType }
     *     
     */
    public CSubLineCodeType getCSubLineCode() {
        return cSubLineCode;
    }

    /**
     * Sets the value of the cSubLineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSubLineCodeType }
     *     
     */
    public void setCSubLineCode(CSubLineCodeType value) {
        this.cSubLineCode = value;
    }

    /**
     * Gets the value of the fullTermPremium property.
     * 
     * @return
     *     possible object is
     *     {@link FullTermPremiumType }
     *     
     */
    public FullTermPremiumType getFullTermPremium() {
        return fullTermPremium;
    }

    /**
     * Sets the value of the fullTermPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTermPremiumType }
     *     
     */
    public void setFullTermPremium(FullTermPremiumType value) {
        this.fullTermPremium = value;
    }

    /**
     * Gets the value of the isCovManuallyRated property.
     * 
     * @return
     *     possible object is
     *     {@link IsCovManuallyRatedType }
     *     
     */
    public IsCovManuallyRatedType getIsCovManuallyRated() {
        return isCovManuallyRated;
    }

    /**
     * Sets the value of the isCovManuallyRated property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsCovManuallyRatedType }
     *     
     */
    public void setIsCovManuallyRated(IsCovManuallyRatedType value) {
        this.isCovManuallyRated = value;
    }

    /**
     * Gets the value of the isSubToFullyCharge property.
     * 
     * @return
     *     possible object is
     *     {@link IsSubToFullyChargeType }
     *     
     */
    public IsSubToFullyChargeType getIsSubToFullyCharge() {
        return isSubToFullyCharge;
    }

    /**
     * Sets the value of the isSubToFullyCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsSubToFullyChargeType }
     *     
     */
    public void setIsSubToFullyCharge(IsSubToFullyChargeType value) {
        this.isSubToFullyCharge = value;
    }

    /**
     * Gets the value of the isSubToFullyEarn property.
     * 
     * @return
     *     possible object is
     *     {@link IsSubToFullyEarnType }
     *     
     */
    public IsSubToFullyEarnType getIsSubToFullyEarn() {
        return isSubToFullyEarn;
    }

    /**
     * Sets the value of the isSubToFullyEarn property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsSubToFullyEarnType }
     *     
     */
    public void setIsSubToFullyEarn(IsSubToFullyEarnType value) {
        this.isSubToFullyEarn = value;
    }

    /**
     * Gets the value of the lobCode property.
     * 
     * @return
     *     possible object is
     *     {@link LobCodeType }
     *     
     */
    public LobCodeType getLobCode() {
        return lobCode;
    }

    /**
     * Sets the value of the lobCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LobCodeType }
     *     
     */
    public void setLobCode(LobCodeType value) {
        this.lobCode = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodeType }
     *     
     */
    public ProductCodeType getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodeType }
     *     
     */
    public void setProductCode(ProductCodeType value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the riskState property.
     * 
     * @return
     *     possible object is
     *     {@link RiskStateType }
     *     
     */
    public RiskStateType getRiskState() {
        return riskState;
    }

    /**
     * Sets the value of the riskState property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskStateType }
     *     
     */
    public void setRiskState(RiskStateType value) {
        this.riskState = value;
    }

    /**
     * Gets the value of the riskStateStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link RiskStateStatCodeType }
     *     
     */
    public RiskStateStatCodeType getRiskStateStatCode() {
        return riskStateStatCode;
    }

    /**
     * Sets the value of the riskStateStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskStateStatCodeType }
     *     
     */
    public void setRiskStateStatCode(RiskStateStatCodeType value) {
        this.riskStateStatCode = value;
    }

    /**
     * Gets the value of the transactionPremium property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionPremiumType }
     *     
     */
    public TransactionPremiumType getTransactionPremium() {
        return transactionPremium;
    }

    /**
     * Sets the value of the transactionPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionPremiumType }
     *     
     */
    public void setTransactionPremium(TransactionPremiumType value) {
        this.transactionPremium = value;
    }

    /**
     * Gets the value of the transPremNotSubToAud property.
     * 
     * @return
     *     possible object is
     *     {@link TransPremNotSubToAudType }
     *     
     */
    public TransPremNotSubToAudType getTransPremNotSubToAud() {
        return transPremNotSubToAud;
    }

    /**
     * Sets the value of the transPremNotSubToAud property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransPremNotSubToAudType }
     *     
     */
    public void setTransPremNotSubToAud(TransPremNotSubToAudType value) {
        this.transPremNotSubToAud = value;
    }

    /**
     * Gets the value of the waivedPremium property.
     * 
     * @return
     *     possible object is
     *     {@link WaivedPremiumType }
     *     
     */
    public WaivedPremiumType getWaivedPremium() {
        return waivedPremium;
    }

    /**
     * Sets the value of the waivedPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaivedPremiumType }
     *     
     */
    public void setWaivedPremium(WaivedPremiumType value) {
        this.waivedPremium = value;
    }

    /**
     * Gets the value of the writtenPremium property.
     * 
     * @return
     *     possible object is
     *     {@link WrittenPremiumType }
     *     
     */
    public WrittenPremiumType getWrittenPremium() {
        return writtenPremium;
    }

    /**
     * Sets the value of the writtenPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link WrittenPremiumType }
     *     
     */
    public void setWrittenPremium(WrittenPremiumType value) {
        this.writtenPremium = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the entityReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityReference() {
        return entityReference;
    }

    /**
     * Sets the value of the entityReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityReference(String value) {
        this.entityReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGid(Integer value) {
        this.gid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the refValue property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRefValue() {
        return refValue;
    }

    /**
     * Sets the value of the refValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRefValue(Short value) {
        this.refValue = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

}
