//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MediaLiabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaLiabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnnualPremium" type="{}AnnualPremiumType"/>
 *         &lt;element name="BalanceToMinimum" type="{}BalanceToMinimumType"/>
 *         &lt;element name="CommissionablePremium" type="{}CommissionablePremiumType"/>
 *         &lt;element name="CExposureBase" type="{}CExposureBaseType"/>
 *         &lt;element name="CLobDateDesForReset" type="{}CLobDateDesForResetType"/>
 *         &lt;element name="CRiskModifierType" type="{}CRiskModifierTypeType"/>
 *         &lt;element name="FullTermPremium" type="{}FullTermPremiumType"/>
 *         &lt;element name="IsCovManuallyRated" type="{}IsCovManuallyRatedType"/>
 *         &lt;element name="LobCode" type="{}LobCodeType"/>
 *         &lt;element name="ProductCode" type="{}ProductCodeType"/>
 *         &lt;element name="RiskState" type="{}RiskStateType"/>
 *         &lt;element name="TransactionPremium" type="{}TransactionPremiumType"/>
 *         &lt;element name="TransPremNotSubToAud" type="{}TransPremNotSubToAudType"/>
 *         &lt;element name="WaivedPremium" type="{}WaivedPremiumType"/>
 *         &lt;element name="WrittenPremium" type="{}WrittenPremiumType"/>
 *         &lt;element name="MDHeaderInformationList" type="{}MDHeaderInformationListType"/>
 *         &lt;element name="MDExposureInformationList" type="{}MDExposureInformationListType"/>
 *         &lt;element name="MDRiskModifierList" type="{}MDRiskModifierListType"/>
 *         &lt;element name="MDRiskCharacteristicsNonFinancialList" type="{}MDRiskCharacteristicsNonFinancialListType"/>
 *         &lt;element name="MDFinancialAnalysisList" type="{}MDFinancialAnalysisListType"/>
 *         &lt;element name="MDScheduleRatingList" type="{}MDScheduleRatingListType"/>
 *         &lt;element name="MDSignificantTermsAndConditionAdditonalCoverageList" type="{}MDSignificantTermsAndConditionAdditonalCoverageListType"/>
 *         &lt;element name="MDCoverageStructureList" type="{}MDCoverageStructureListType"/>
 *         &lt;element name="MDRatingDetailsList" type="{}MDRatingDetailsListType"/>
 *         &lt;element name="MDPremiumSummaryDetailList" type="{}MDPremiumSummaryDetailListType"/>
 *         &lt;element name="MDUnderwritingCommentsList" type="{}MDUnderwritingCommentsListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EntityReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="RefName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RefValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaLiabilityType", propOrder = {
    "annualPremium",
    "balanceToMinimum",
    "commissionablePremium",
    "cExposureBase",
    "cLobDateDesForReset",
    "cRiskModifierType",
    "fullTermPremium",
    "isCovManuallyRated",
    "lobCode",
    "productCode",
    "riskState",
    "transactionPremium",
    "transPremNotSubToAud",
    "waivedPremium",
    "writtenPremium",
    "mdHeaderInformationList",
    "mdExposureInformationList",
    "mdRiskModifierList",
    "mdRiskCharacteristicsNonFinancialList",
    "mdFinancialAnalysisList",
    "mdScheduleRatingList",
    "mdSignificantTermsAndConditionAdditonalCoverageList",
    "mdCoverageStructureList",
    "mdRatingDetailsList",
    "mdPremiumSummaryDetailList",
    "mdUnderwritingCommentsList"
})
public class MediaLiabilityType {

    @XmlElement(name = "AnnualPremium", required = true)
    protected AnnualPremiumType annualPremium;
    @XmlElement(name = "BalanceToMinimum", required = true)
    protected BalanceToMinimumType balanceToMinimum;
    @XmlElement(name = "CommissionablePremium", required = true)
    protected CommissionablePremiumType commissionablePremium;
    @XmlElement(name = "CExposureBase", required = true)
    protected CExposureBaseType cExposureBase;
    @XmlElement(name = "CLobDateDesForReset", required = true)
    protected CLobDateDesForResetType cLobDateDesForReset;
    @XmlElement(name = "CRiskModifierType", required = true)
    protected CRiskModifierTypeType cRiskModifierType;
    @XmlElement(name = "FullTermPremium", required = true)
    protected FullTermPremiumType fullTermPremium;
    @XmlElement(name = "IsCovManuallyRated", required = true)
    protected IsCovManuallyRatedType isCovManuallyRated;
    @XmlElement(name = "LobCode", required = true)
    protected LobCodeType lobCode;
    @XmlElement(name = "ProductCode", required = true)
    protected ProductCodeType productCode;
    @XmlElement(name = "RiskState", required = true)
    protected RiskStateType riskState;
    @XmlElement(name = "TransactionPremium", required = true)
    protected TransactionPremiumType transactionPremium;
    @XmlElement(name = "TransPremNotSubToAud", required = true)
    protected TransPremNotSubToAudType transPremNotSubToAud;
    @XmlElement(name = "WaivedPremium", required = true)
    protected WaivedPremiumType waivedPremium;
    @XmlElement(name = "WrittenPremium", required = true)
    protected WrittenPremiumType writtenPremium;
    @XmlElement(name = "MDHeaderInformationList", required = true)
    protected MDHeaderInformationListType mdHeaderInformationList;
    @XmlElement(name = "MDExposureInformationList", required = true)
    protected MDExposureInformationListType mdExposureInformationList;
    @XmlElement(name = "MDRiskModifierList", required = true)
    protected MDRiskModifierListType mdRiskModifierList;
    @XmlElement(name = "MDRiskCharacteristicsNonFinancialList", required = true)
    protected MDRiskCharacteristicsNonFinancialListType mdRiskCharacteristicsNonFinancialList;
    @XmlElement(name = "MDFinancialAnalysisList", required = true)
    protected MDFinancialAnalysisListType mdFinancialAnalysisList;
    @XmlElement(name = "MDScheduleRatingList", required = true)
    protected MDScheduleRatingListType mdScheduleRatingList;
    @XmlElement(name = "MDSignificantTermsAndConditionAdditonalCoverageList", required = true)
    protected MDSignificantTermsAndConditionAdditonalCoverageListType mdSignificantTermsAndConditionAdditonalCoverageList;
    @XmlElement(name = "MDCoverageStructureList", required = true)
    protected MDCoverageStructureListType mdCoverageStructureList;
    @XmlElement(name = "MDRatingDetailsList", required = true)
    protected MDRatingDetailsListType mdRatingDetailsList;
    @XmlElement(name = "MDPremiumSummaryDetailList", required = true)
    protected MDPremiumSummaryDetailListType mdPremiumSummaryDetailList;
    @XmlElement(name = "MDUnderwritingCommentsList", required = true)
    protected MDUnderwritingCommentsListType mdUnderwritingCommentsList;
    @XmlAttribute(name = "DateCreated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlAttribute(name = "EntityReference")
    protected String entityReference;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "Gid")
    protected Short gid;
    @XmlAttribute(name = "Id")
    protected Short id;
    @XmlAttribute(name = "RefName")
    protected String refName;
    @XmlAttribute(name = "RefValue")
    protected Integer refValue;
    @XmlAttribute(name = "UserCreated")
    protected String userCreated;

    /**
     * Gets the value of the annualPremium property.
     * 
     * @return
     *     possible object is
     *     {@link AnnualPremiumType }
     *     
     */
    public AnnualPremiumType getAnnualPremium() {
        return annualPremium;
    }

    /**
     * Sets the value of the annualPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnualPremiumType }
     *     
     */
    public void setAnnualPremium(AnnualPremiumType value) {
        this.annualPremium = value;
    }

    /**
     * Gets the value of the balanceToMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceToMinimumType }
     *     
     */
    public BalanceToMinimumType getBalanceToMinimum() {
        return balanceToMinimum;
    }

    /**
     * Sets the value of the balanceToMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceToMinimumType }
     *     
     */
    public void setBalanceToMinimum(BalanceToMinimumType value) {
        this.balanceToMinimum = value;
    }

    /**
     * Gets the value of the commissionablePremium property.
     * 
     * @return
     *     possible object is
     *     {@link CommissionablePremiumType }
     *     
     */
    public CommissionablePremiumType getCommissionablePremium() {
        return commissionablePremium;
    }

    /**
     * Sets the value of the commissionablePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommissionablePremiumType }
     *     
     */
    public void setCommissionablePremium(CommissionablePremiumType value) {
        this.commissionablePremium = value;
    }

    /**
     * Gets the value of the cExposureBase property.
     * 
     * @return
     *     possible object is
     *     {@link CExposureBaseType }
     *     
     */
    public CExposureBaseType getCExposureBase() {
        return cExposureBase;
    }

    /**
     * Sets the value of the cExposureBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link CExposureBaseType }
     *     
     */
    public void setCExposureBase(CExposureBaseType value) {
        this.cExposureBase = value;
    }

    /**
     * Gets the value of the cLobDateDesForReset property.
     * 
     * @return
     *     possible object is
     *     {@link CLobDateDesForResetType }
     *     
     */
    public CLobDateDesForResetType getCLobDateDesForReset() {
        return cLobDateDesForReset;
    }

    /**
     * Sets the value of the cLobDateDesForReset property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLobDateDesForResetType }
     *     
     */
    public void setCLobDateDesForReset(CLobDateDesForResetType value) {
        this.cLobDateDesForReset = value;
    }

    /**
     * Gets the value of the cRiskModifierType property.
     * 
     * @return
     *     possible object is
     *     {@link CRiskModifierTypeType }
     *     
     */
    public CRiskModifierTypeType getCRiskModifierType() {
        return cRiskModifierType;
    }

    /**
     * Sets the value of the cRiskModifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRiskModifierTypeType }
     *     
     */
    public void setCRiskModifierType(CRiskModifierTypeType value) {
        this.cRiskModifierType = value;
    }

    /**
     * Gets the value of the fullTermPremium property.
     * 
     * @return
     *     possible object is
     *     {@link FullTermPremiumType }
     *     
     */
    public FullTermPremiumType getFullTermPremium() {
        return fullTermPremium;
    }

    /**
     * Sets the value of the fullTermPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTermPremiumType }
     *     
     */
    public void setFullTermPremium(FullTermPremiumType value) {
        this.fullTermPremium = value;
    }

    /**
     * Gets the value of the isCovManuallyRated property.
     * 
     * @return
     *     possible object is
     *     {@link IsCovManuallyRatedType }
     *     
     */
    public IsCovManuallyRatedType getIsCovManuallyRated() {
        return isCovManuallyRated;
    }

    /**
     * Sets the value of the isCovManuallyRated property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsCovManuallyRatedType }
     *     
     */
    public void setIsCovManuallyRated(IsCovManuallyRatedType value) {
        this.isCovManuallyRated = value;
    }

    /**
     * Gets the value of the lobCode property.
     * 
     * @return
     *     possible object is
     *     {@link LobCodeType }
     *     
     */
    public LobCodeType getLobCode() {
        return lobCode;
    }

    /**
     * Sets the value of the lobCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LobCodeType }
     *     
     */
    public void setLobCode(LobCodeType value) {
        this.lobCode = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodeType }
     *     
     */
    public ProductCodeType getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodeType }
     *     
     */
    public void setProductCode(ProductCodeType value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the riskState property.
     * 
     * @return
     *     possible object is
     *     {@link RiskStateType }
     *     
     */
    public RiskStateType getRiskState() {
        return riskState;
    }

    /**
     * Sets the value of the riskState property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskStateType }
     *     
     */
    public void setRiskState(RiskStateType value) {
        this.riskState = value;
    }

    /**
     * Gets the value of the transactionPremium property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionPremiumType }
     *     
     */
    public TransactionPremiumType getTransactionPremium() {
        return transactionPremium;
    }

    /**
     * Sets the value of the transactionPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionPremiumType }
     *     
     */
    public void setTransactionPremium(TransactionPremiumType value) {
        this.transactionPremium = value;
    }

    /**
     * Gets the value of the transPremNotSubToAud property.
     * 
     * @return
     *     possible object is
     *     {@link TransPremNotSubToAudType }
     *     
     */
    public TransPremNotSubToAudType getTransPremNotSubToAud() {
        return transPremNotSubToAud;
    }

    /**
     * Sets the value of the transPremNotSubToAud property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransPremNotSubToAudType }
     *     
     */
    public void setTransPremNotSubToAud(TransPremNotSubToAudType value) {
        this.transPremNotSubToAud = value;
    }

    /**
     * Gets the value of the waivedPremium property.
     * 
     * @return
     *     possible object is
     *     {@link WaivedPremiumType }
     *     
     */
    public WaivedPremiumType getWaivedPremium() {
        return waivedPremium;
    }

    /**
     * Sets the value of the waivedPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaivedPremiumType }
     *     
     */
    public void setWaivedPremium(WaivedPremiumType value) {
        this.waivedPremium = value;
    }

    /**
     * Gets the value of the writtenPremium property.
     * 
     * @return
     *     possible object is
     *     {@link WrittenPremiumType }
     *     
     */
    public WrittenPremiumType getWrittenPremium() {
        return writtenPremium;
    }

    /**
     * Sets the value of the writtenPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link WrittenPremiumType }
     *     
     */
    public void setWrittenPremium(WrittenPremiumType value) {
        this.writtenPremium = value;
    }

    /**
     * Gets the value of the mdHeaderInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link MDHeaderInformationListType }
     *     
     */
    public MDHeaderInformationListType getMDHeaderInformationList() {
        return mdHeaderInformationList;
    }

    /**
     * Sets the value of the mdHeaderInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDHeaderInformationListType }
     *     
     */
    public void setMDHeaderInformationList(MDHeaderInformationListType value) {
        this.mdHeaderInformationList = value;
    }

    /**
     * Gets the value of the mdExposureInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link MDExposureInformationListType }
     *     
     */
    public MDExposureInformationListType getMDExposureInformationList() {
        return mdExposureInformationList;
    }

    /**
     * Sets the value of the mdExposureInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDExposureInformationListType }
     *     
     */
    public void setMDExposureInformationList(MDExposureInformationListType value) {
        this.mdExposureInformationList = value;
    }

    /**
     * Gets the value of the mdRiskModifierList property.
     * 
     * @return
     *     possible object is
     *     {@link MDRiskModifierListType }
     *     
     */
    public MDRiskModifierListType getMDRiskModifierList() {
        return mdRiskModifierList;
    }

    /**
     * Sets the value of the mdRiskModifierList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDRiskModifierListType }
     *     
     */
    public void setMDRiskModifierList(MDRiskModifierListType value) {
        this.mdRiskModifierList = value;
    }

    /**
     * Gets the value of the mdRiskCharacteristicsNonFinancialList property.
     * 
     * @return
     *     possible object is
     *     {@link MDRiskCharacteristicsNonFinancialListType }
     *     
     */
    public MDRiskCharacteristicsNonFinancialListType getMDRiskCharacteristicsNonFinancialList() {
        return mdRiskCharacteristicsNonFinancialList;
    }

    /**
     * Sets the value of the mdRiskCharacteristicsNonFinancialList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDRiskCharacteristicsNonFinancialListType }
     *     
     */
    public void setMDRiskCharacteristicsNonFinancialList(MDRiskCharacteristicsNonFinancialListType value) {
        this.mdRiskCharacteristicsNonFinancialList = value;
    }

    /**
     * Gets the value of the mdFinancialAnalysisList property.
     * 
     * @return
     *     possible object is
     *     {@link MDFinancialAnalysisListType }
     *     
     */
    public MDFinancialAnalysisListType getMDFinancialAnalysisList() {
        return mdFinancialAnalysisList;
    }

    /**
     * Sets the value of the mdFinancialAnalysisList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDFinancialAnalysisListType }
     *     
     */
    public void setMDFinancialAnalysisList(MDFinancialAnalysisListType value) {
        this.mdFinancialAnalysisList = value;
    }

    /**
     * Gets the value of the mdScheduleRatingList property.
     * 
     * @return
     *     possible object is
     *     {@link MDScheduleRatingListType }
     *     
     */
    public MDScheduleRatingListType getMDScheduleRatingList() {
        return mdScheduleRatingList;
    }

    /**
     * Sets the value of the mdScheduleRatingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDScheduleRatingListType }
     *     
     */
    public void setMDScheduleRatingList(MDScheduleRatingListType value) {
        this.mdScheduleRatingList = value;
    }

    /**
     * Gets the value of the mdSignificantTermsAndConditionAdditonalCoverageList property.
     * 
     * @return
     *     possible object is
     *     {@link MDSignificantTermsAndConditionAdditonalCoverageListType }
     *     
     */
    public MDSignificantTermsAndConditionAdditonalCoverageListType getMDSignificantTermsAndConditionAdditonalCoverageList() {
        return mdSignificantTermsAndConditionAdditonalCoverageList;
    }

    /**
     * Sets the value of the mdSignificantTermsAndConditionAdditonalCoverageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDSignificantTermsAndConditionAdditonalCoverageListType }
     *     
     */
    public void setMDSignificantTermsAndConditionAdditonalCoverageList(MDSignificantTermsAndConditionAdditonalCoverageListType value) {
        this.mdSignificantTermsAndConditionAdditonalCoverageList = value;
    }

    /**
     * Gets the value of the mdCoverageStructureList property.
     * 
     * @return
     *     possible object is
     *     {@link MDCoverageStructureListType }
     *     
     */
    public MDCoverageStructureListType getMDCoverageStructureList() {
        return mdCoverageStructureList;
    }

    /**
     * Sets the value of the mdCoverageStructureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCoverageStructureListType }
     *     
     */
    public void setMDCoverageStructureList(MDCoverageStructureListType value) {
        this.mdCoverageStructureList = value;
    }

    /**
     * Gets the value of the mdRatingDetailsList property.
     * 
     * @return
     *     possible object is
     *     {@link MDRatingDetailsListType }
     *     
     */
    public MDRatingDetailsListType getMDRatingDetailsList() {
        return mdRatingDetailsList;
    }

    /**
     * Sets the value of the mdRatingDetailsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDRatingDetailsListType }
     *     
     */
    public void setMDRatingDetailsList(MDRatingDetailsListType value) {
        this.mdRatingDetailsList = value;
    }

    /**
     * Gets the value of the mdPremiumSummaryDetailList property.
     * 
     * @return
     *     possible object is
     *     {@link MDPremiumSummaryDetailListType }
     *     
     */
    public MDPremiumSummaryDetailListType getMDPremiumSummaryDetailList() {
        return mdPremiumSummaryDetailList;
    }

    /**
     * Sets the value of the mdPremiumSummaryDetailList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDPremiumSummaryDetailListType }
     *     
     */
    public void setMDPremiumSummaryDetailList(MDPremiumSummaryDetailListType value) {
        this.mdPremiumSummaryDetailList = value;
    }

    /**
     * Gets the value of the mdUnderwritingCommentsList property.
     * 
     * @return
     *     possible object is
     *     {@link MDUnderwritingCommentsListType }
     *     
     */
    public MDUnderwritingCommentsListType getMDUnderwritingCommentsList() {
        return mdUnderwritingCommentsList;
    }

    /**
     * Sets the value of the mdUnderwritingCommentsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDUnderwritingCommentsListType }
     *     
     */
    public void setMDUnderwritingCommentsList(MDUnderwritingCommentsListType value) {
        this.mdUnderwritingCommentsList = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the entityReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityReference() {
        return entityReference;
    }

    /**
     * Sets the value of the entityReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityReference(String value) {
        this.entityReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setGid(Short value) {
        this.gid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
    }

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the refValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefValue() {
        return refValue;
    }

    /**
     * Sets the value of the refValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefValue(Integer value) {
        this.refValue = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

}
