//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MLPLLinesOfBusinessListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MLPLLinesOfBusinessListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MLPLLinesOfBusiness" type="{}MLPLLinesOfBusinessType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MLPLLinesOfBusinessListType", propOrder = {
    "mlplLinesOfBusiness"
})
public class MLPLLinesOfBusinessListType {

    @XmlElement(name = "MLPLLinesOfBusiness")
    protected List<MLPLLinesOfBusinessType> mlplLinesOfBusiness;

    /**
     * Gets the value of the mlplLinesOfBusiness property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mlplLinesOfBusiness property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMLPLLinesOfBusiness().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MLPLLinesOfBusinessType }
     * 
     * 
     */
    public List<MLPLLinesOfBusinessType> getMLPLLinesOfBusiness() {
        if (mlplLinesOfBusiness == null) {
            mlplLinesOfBusiness = new ArrayList<MLPLLinesOfBusinessType>();
        }
        return this.mlplLinesOfBusiness;
    }

}
