//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ameet.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QuotePolicyList_QNAME = new QName("", "QuotePolicyList");
    private final static QName _CommissionTypeUserModified_QNAME = new QName("", "UserModified");
    private final static QName _CommissionTypeCommPlanComm_QNAME = new QName("", "CommPlanComm");
    private final static QName _CommissionTypeCommPlanDesc_QNAME = new QName("", "CommPlanDesc");
    private final static QName _CommissionTypeUserCreated_QNAME = new QName("", "UserCreated");
    private final static QName _CommissionTypeCommPlanName_QNAME = new QName("", "CommPlanName");
    private final static QName _CommissionTypeCommission_QNAME = new QName("", "Commission");
    private final static QName _CommissionTypeDateCreated_QNAME = new QName("", "DateCreated");
    private final static QName _CommissionTypePolicyReference_QNAME = new QName("", "PolicyReference");
    private final static QName _CommissionTypeNetCommission_QNAME = new QName("", "NetCommission");
    private final static QName _CommissionTypeIsCommPlanTired_QNAME = new QName("", "IsCommPlanTired");
    private final static QName _CommissionTypeType_QNAME = new QName("", "Type");
    private final static QName _CommissionTypeIsCommPlanPercent_QNAME = new QName("", "IsCommPlanPercent");
    private final static QName _CommissionTypeId_QNAME = new QName("", "Id");
    private final static QName _CommissionTypeProducerCode_QNAME = new QName("", "ProducerCode");
    private final static QName _CommissionTypeDateModified_QNAME = new QName("", "DateModified");
    private final static QName _CommissionTypeCommPlanId_QNAME = new QName("", "CommPlanId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ameet.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuotePolicyListType }
     * 
     */
    public QuotePolicyListType createQuotePolicyListType() {
        return new QuotePolicyListType();
    }

    /**
     * Create an instance of {@link CHasLobEpType }
     * 
     */
    public CHasLobEpType createCHasLobEpType() {
        return new CHasLobEpType();
    }

    /**
     * Create an instance of {@link CLobDescriptionType }
     * 
     */
    public CLobDescriptionType createCLobDescriptionType() {
        return new CLobDescriptionType();
    }

    /**
     * Create an instance of {@link CFinalFactorType }
     * 
     */
    public CFinalFactorType createCFinalFactorType() {
        return new CFinalFactorType();
    }

    /**
     * Create an instance of {@link COpportunityIdType }
     * 
     */
    public COpportunityIdType createCOpportunityIdType() {
        return new COpportunityIdType();
    }

    /**
     * Create an instance of {@link BookingDateType }
     * 
     */
    public BookingDateType createBookingDateType() {
        return new BookingDateType();
    }

    /**
     * Create an instance of {@link AruType }
     * 
     */
    public AruType createAruType() {
        return new AruType();
    }

    /**
     * Create an instance of {@link CSelectedLobLimitType }
     * 
     */
    public CSelectedLobLimitType createCSelectedLobLimitType() {
        return new CSelectedLobLimitType();
    }

    /**
     * Create an instance of {@link CPaperTypeDescType }
     * 
     */
    public CPaperTypeDescType createCPaperTypeDescType() {
        return new CPaperTypeDescType();
    }

    /**
     * Create an instance of {@link CCompanyTypeType }
     * 
     */
    public CCompanyTypeType createCCompanyTypeType() {
        return new CCompanyTypeType();
    }

    /**
     * Create an instance of {@link CTailDtType }
     * 
     */
    public CTailDtType createCTailDtType() {
        return new CTailDtType();
    }

    /**
     * Create an instance of {@link CMaxFactorType }
     * 
     */
    public CMaxFactorType createCMaxFactorType() {
        return new CMaxFactorType();
    }

    /**
     * Create an instance of {@link CharactersticsMinMaxDetailsListType }
     * 
     */
    public CharactersticsMinMaxDetailsListType createCharactersticsMinMaxDetailsListType() {
        return new CharactersticsMinMaxDetailsListType();
    }

    /**
     * Create an instance of {@link CHeaderInsuredInfoType }
     * 
     */
    public CHeaderInsuredInfoType createCHeaderInsuredInfoType() {
        return new CHeaderInsuredInfoType();
    }

    /**
     * Create an instance of {@link MDPremiumSummaryDetailType }
     * 
     */
    public MDPremiumSummaryDetailType createMDPremiumSummaryDetailType() {
        return new MDPremiumSummaryDetailType();
    }

    /**
     * Create an instance of {@link NameTypeStatCodeType }
     * 
     */
    public NameTypeStatCodeType createNameTypeStatCodeType() {
        return new NameTypeStatCodeType();
    }

    /**
     * Create an instance of {@link PayorCityType }
     * 
     */
    public PayorCityType createPayorCityType() {
        return new PayorCityType();
    }

    /**
     * Create an instance of {@link CDisplayCurrentType }
     * 
     */
    public CDisplayCurrentType createCDisplayCurrentType() {
        return new CDisplayCurrentType();
    }

    /**
     * Create an instance of {@link CreateShellAccountType }
     * 
     */
    public CreateShellAccountType createCreateShellAccountType() {
        return new CreateShellAccountType();
    }

    /**
     * Create an instance of {@link UserCreatedType }
     * 
     */
    public UserCreatedType createUserCreatedType() {
        return new UserCreatedType();
    }

    /**
     * Create an instance of {@link PaymentPlanDescriptionType }
     * 
     */
    public PaymentPlanDescriptionType createPaymentPlanDescriptionType() {
        return new PaymentPlanDescriptionType();
    }

    /**
     * Create an instance of {@link IsCommPlanPercentType }
     * 
     */
    public IsCommPlanPercentType createIsCommPlanPercentType() {
        return new IsCommPlanPercentType();
    }

    /**
     * Create an instance of {@link MasterQuoteType }
     * 
     */
    public MasterQuoteType createMasterQuoteType() {
        return new MasterQuoteType();
    }

    /**
     * Create an instance of {@link MarketSegmentCodeType }
     * 
     */
    public MarketSegmentCodeType createMarketSegmentCodeType() {
        return new MarketSegmentCodeType();
    }

    /**
     * Create an instance of {@link PolicyUnderwriterListType }
     * 
     */
    public PolicyUnderwriterListType createPolicyUnderwriterListType() {
        return new PolicyUnderwriterListType();
    }

    /**
     * Create an instance of {@link IncludeType }
     * 
     */
    public IncludeType createIncludeType() {
        return new IncludeType();
    }

    /**
     * Create an instance of {@link CPremCategoryType }
     * 
     */
    public CPremCategoryType createCPremCategoryType() {
        return new CPremCategoryType();
    }

    /**
     * Create an instance of {@link QuoteUWCommentsType }
     * 
     */
    public QuoteUWCommentsType createQuoteUWCommentsType() {
        return new QuoteUWCommentsType();
    }

    /**
     * Create an instance of {@link CDesSortOrderType }
     * 
     */
    public CDesSortOrderType createCDesSortOrderType() {
        return new CDesSortOrderType();
    }

    /**
     * Create an instance of {@link BROKERCONTACTType }
     * 
     */
    public BROKERCONTACTType createBROKERCONTACTType() {
        return new BROKERCONTACTType();
    }

    /**
     * Create an instance of {@link MDRiskCharacteristicsNonFinancialType }
     * 
     */
    public MDRiskCharacteristicsNonFinancialType createMDRiskCharacteristicsNonFinancialType() {
        return new MDRiskCharacteristicsNonFinancialType();
    }

    /**
     * Create an instance of {@link CLegalEntityCdType }
     * 
     */
    public CLegalEntityCdType createCLegalEntityCdType() {
        return new CLegalEntityCdType();
    }

    /**
     * Create an instance of {@link CityType }
     * 
     */
    public CityType createCityType() {
        return new CityType();
    }

    /**
     * Create an instance of {@link IsDeregulatedType }
     * 
     */
    public IsDeregulatedType createIsDeregulatedType() {
        return new IsDeregulatedType();
    }

    /**
     * Create an instance of {@link CEffectiveDateType }
     * 
     */
    public CEffectiveDateType createCEffectiveDateType() {
        return new CEffectiveDateType();
    }

    /**
     * Create an instance of {@link PayorIdType }
     * 
     */
    public PayorIdType createPayorIdType() {
        return new PayorIdType();
    }

    /**
     * Create an instance of {@link OldEntityTypeType }
     * 
     */
    public OldEntityTypeType createOldEntityTypeType() {
        return new OldEntityTypeType();
    }

    /**
     * Create an instance of {@link SicCodeType }
     * 
     */
    public SicCodeType createSicCodeType() {
        return new SicCodeType();
    }

    /**
     * Create an instance of {@link TotalSurchargeFtermType }
     * 
     */
    public TotalSurchargeFtermType createTotalSurchargeFtermType() {
        return new TotalSurchargeFtermType();
    }

    /**
     * Create an instance of {@link QBPolicyDynamicFormDataType }
     * 
     */
    public QBPolicyDynamicFormDataType createQBPolicyDynamicFormDataType() {
        return new QBPolicyDynamicFormDataType();
    }

    /**
     * Create an instance of {@link PayorZipType }
     * 
     */
    public PayorZipType createPayorZipType() {
        return new PayorZipType();
    }

    /**
     * Create an instance of {@link NoConflictOnRollfwdType }
     * 
     */
    public NoConflictOnRollfwdType createNoConflictOnRollfwdType() {
        return new NoConflictOnRollfwdType();
    }

    /**
     * Create an instance of {@link IsSubjectToAuditType }
     * 
     */
    public IsSubjectToAuditType createIsSubjectToAuditType() {
        return new IsSubjectToAuditType();
    }

    /**
     * Create an instance of {@link CRevenueType }
     * 
     */
    public CRevenueType createCRevenueType() {
        return new CRevenueType();
    }

    /**
     * Create an instance of {@link BookingUserType }
     * 
     */
    public BookingUserType createBookingUserType() {
        return new BookingUserType();
    }

    /**
     * Create an instance of {@link CCharecteristicTypeUkType }
     * 
     */
    public CCharecteristicTypeUkType createCCharecteristicTypeUkType() {
        return new CCharecteristicTypeUkType();
    }

    /**
     * Create an instance of {@link QuoteNumberType }
     * 
     */
    public QuoteNumberType createQuoteNumberType() {
        return new QuoteNumberType();
    }

    /**
     * Create an instance of {@link CCoverageStructureUkType }
     * 
     */
    public CCoverageStructureUkType createCCoverageStructureUkType() {
        return new CCoverageStructureUkType();
    }

    /**
     * Create an instance of {@link SubjectivitiesType }
     * 
     */
    public SubjectivitiesType createSubjectivitiesType() {
        return new SubjectivitiesType();
    }

    /**
     * Create an instance of {@link CHomeOfficePhoneType }
     * 
     */
    public CHomeOfficePhoneType createCHomeOfficePhoneType() {
        return new CHomeOfficePhoneType();
    }

    /**
     * Create an instance of {@link MDSignificantTermsAndConditionAdditonalCoverageType }
     * 
     */
    public MDSignificantTermsAndConditionAdditonalCoverageType createMDSignificantTermsAndConditionAdditonalCoverageType() {
        return new MDSignificantTermsAndConditionAdditonalCoverageType();
    }

    /**
     * Create an instance of {@link InsuredListType }
     * 
     */
    public InsuredListType createInsuredListType() {
        return new InsuredListType();
    }

    /**
     * Create an instance of {@link CScheduledMediaType }
     * 
     */
    public CScheduledMediaType createCScheduledMediaType() {
        return new CScheduledMediaType();
    }

    /**
     * Create an instance of {@link RevisionNumberType }
     * 
     */
    public RevisionNumberType createRevisionNumberType() {
        return new RevisionNumberType();
    }

    /**
     * Create an instance of {@link DateCreatedType }
     * 
     */
    public DateCreatedType createDateCreatedType() {
        return new DateCreatedType();
    }

    /**
     * Create an instance of {@link GoodStandingType }
     * 
     */
    public GoodStandingType createGoodStandingType() {
        return new GoodStandingType();
    }

    /**
     * Create an instance of {@link CBuildingType }
     * 
     */
    public CBuildingType createCBuildingType() {
        return new CBuildingType();
    }

    /**
     * Create an instance of {@link PaymentPlanIdType }
     * 
     */
    public PaymentPlanIdType createPaymentPlanIdType() {
        return new PaymentPlanIdType();
    }

    /**
     * Create an instance of {@link CStreet1Type }
     * 
     */
    public CStreet1Type createCStreet1Type() {
        return new CStreet1Type();
    }

    /**
     * Create an instance of {@link InstallmentIdType }
     * 
     */
    public InstallmentIdType createInstallmentIdType() {
        return new InstallmentIdType();
    }

    /**
     * Create an instance of {@link PayorPhoneType }
     * 
     */
    public PayorPhoneType createPayorPhoneType() {
        return new PayorPhoneType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ZipCodeType }
     * 
     */
    public ZipCodeType createZipCodeType() {
        return new ZipCodeType();
    }

    /**
     * Create an instance of {@link CLobIsoCounterType }
     * 
     */
    public CLobIsoCounterType createCLobIsoCounterType() {
        return new CLobIsoCounterType();
    }

    /**
     * Create an instance of {@link TotalFtermColFeeType }
     * 
     */
    public TotalFtermColFeeType createTotalFtermColFeeType() {
        return new TotalFtermColFeeType();
    }

    /**
     * Create an instance of {@link CHeaderType }
     * 
     */
    public CHeaderType createCHeaderType() {
        return new CHeaderType();
    }

    /**
     * Create an instance of {@link InstallmentType }
     * 
     */
    public InstallmentType createInstallmentType() {
        return new InstallmentType();
    }

    /**
     * Create an instance of {@link ContactNameType }
     * 
     */
    public ContactNameType createContactNameType() {
        return new ContactNameType();
    }

    /**
     * Create an instance of {@link CFinalPremDispType }
     * 
     */
    public CFinalPremDispType createCFinalPremDispType() {
        return new CFinalPremDispType();
    }

    /**
     * Create an instance of {@link CustomRevisionNumberType }
     * 
     */
    public CustomRevisionNumberType createCustomRevisionNumberType() {
        return new CustomRevisionNumberType();
    }

    /**
     * Create an instance of {@link CRatingDtlItemCodeType }
     * 
     */
    public CRatingDtlItemCodeType createCRatingDtlItemCodeType() {
        return new CRatingDtlItemCodeType();
    }

    /**
     * Create an instance of {@link IsSubToFullyChargeType }
     * 
     */
    public IsSubToFullyChargeType createIsSubToFullyChargeType() {
        return new IsSubToFullyChargeType();
    }

    /**
     * Create an instance of {@link TotalAnnualFeeType }
     * 
     */
    public TotalAnnualFeeType createTotalAnnualFeeType() {
        return new TotalAnnualFeeType();
    }

    /**
     * Create an instance of {@link IsComReductType }
     * 
     */
    public IsComReductType createIsComReductType() {
        return new IsComReductType();
    }

    /**
     * Create an instance of {@link StateDescType }
     * 
     */
    public StateDescType createStateDescType() {
        return new StateDescType();
    }

    /**
     * Create an instance of {@link CIsoDescriptionType }
     * 
     */
    public CIsoDescriptionType createCIsoDescriptionType() {
        return new CIsoDescriptionType();
    }

    /**
     * Create an instance of {@link CHasLobClType }
     * 
     */
    public CHasLobClType createCHasLobClType() {
        return new CHasLobClType();
    }

    /**
     * Create an instance of {@link BROKERCONTACTListType }
     * 
     */
    public BROKERCONTACTListType createBROKERCONTACTListType() {
        return new BROKERCONTACTListType();
    }

    /**
     * Create an instance of {@link MarketGroupDescriptionType }
     * 
     */
    public MarketGroupDescriptionType createMarketGroupDescriptionType() {
        return new MarketGroupDescriptionType();
    }

    /**
     * Create an instance of {@link RatingModeType }
     * 
     */
    public RatingModeType createRatingModeType() {
        return new RatingModeType();
    }

    /**
     * Create an instance of {@link DistinguishedFieldUwType }
     * 
     */
    public DistinguishedFieldUwType createDistinguishedFieldUwType() {
        return new DistinguishedFieldUwType();
    }

    /**
     * Create an instance of {@link SurchargeAssessAmountType }
     * 
     */
    public SurchargeAssessAmountType createSurchargeAssessAmountType() {
        return new SurchargeAssessAmountType();
    }

    /**
     * Create an instance of {@link CommPlanNameType }
     * 
     */
    public CommPlanNameType createCommPlanNameType() {
        return new CommPlanNameType();
    }

    /**
     * Create an instance of {@link CRatedPremType }
     * 
     */
    public CRatedPremType createCRatedPremType() {
        return new CRatedPremType();
    }

    /**
     * Create an instance of {@link TotalFtermSurchargeType }
     * 
     */
    public TotalFtermSurchargeType createTotalFtermSurchargeType() {
        return new TotalFtermSurchargeType();
    }

    /**
     * Create an instance of {@link AddressTypeType }
     * 
     */
    public AddressTypeType createAddressTypeType() {
        return new AddressTypeType();
    }

    /**
     * Create an instance of {@link RenewalType }
     * 
     */
    public RenewalType createRenewalType() {
        return new RenewalType();
    }

    /**
     * Create an instance of {@link IndRiskSituationType }
     * 
     */
    public IndRiskSituationType createIndRiskSituationType() {
        return new IndRiskSituationType();
    }

    /**
     * Create an instance of {@link CoverageStructureDetailsType }
     * 
     */
    public CoverageStructureDetailsType createCoverageStructureDetailsType() {
        return new CoverageStructureDetailsType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link CTailDateFlagType }
     * 
     */
    public CTailDateFlagType createCTailDateFlagType() {
        return new CTailDateFlagType();
    }

    /**
     * Create an instance of {@link CAddressStatusType }
     * 
     */
    public CAddressStatusType createCAddressStatusType() {
        return new CAddressStatusType();
    }

    /**
     * Create an instance of {@link BillCollectionMethodIdType }
     * 
     */
    public BillCollectionMethodIdType createBillCollectionMethodIdType() {
        return new BillCollectionMethodIdType();
    }

    /**
     * Create an instance of {@link CountryCodeType }
     * 
     */
    public CountryCodeType createCountryCodeType() {
        return new CountryCodeType();
    }

    /**
     * Create an instance of {@link ProducerOfRecordType }
     * 
     */
    public ProducerOfRecordType createProducerOfRecordType() {
        return new ProducerOfRecordType();
    }

    /**
     * Create an instance of {@link RatingDetailsListType }
     * 
     */
    public RatingDetailsListType createRatingDetailsListType() {
        return new RatingDetailsListType();
    }

    /**
     * Create an instance of {@link CStreet2Type }
     * 
     */
    public CStreet2Type createCStreet2Type() {
        return new CStreet2Type();
    }

    /**
     * Create an instance of {@link PolicyFinancialType }
     * 
     */
    public PolicyFinancialType createPolicyFinancialType() {
        return new PolicyFinancialType();
    }

    /**
     * Create an instance of {@link CDefaultsType }
     * 
     */
    public CDefaultsType createCDefaultsType() {
        return new CDefaultsType();
    }

    /**
     * Create an instance of {@link CompanyNameType }
     * 
     */
    public CompanyNameType createCompanyNameType() {
        return new CompanyNameType();
    }

    /**
     * Create an instance of {@link RetrieveQuoteNumberType }
     * 
     */
    public RetrieveQuoteNumberType createRetrieveQuoteNumberType() {
        return new RetrieveQuoteNumberType();
    }

    /**
     * Create an instance of {@link CGenInfoRevenueType }
     * 
     */
    public CGenInfoRevenueType createCGenInfoRevenueType() {
        return new CGenInfoRevenueType();
    }

    /**
     * Create an instance of {@link CRenwlIndCodeType }
     * 
     */
    public CRenwlIndCodeType createCRenwlIndCodeType() {
        return new CRenwlIndCodeType();
    }

    /**
     * Create an instance of {@link CPaperTypeType }
     * 
     */
    public CPaperTypeType createCPaperTypeType() {
        return new CPaperTypeType();
    }

    /**
     * Create an instance of {@link MDCoverageStructureListType }
     * 
     */
    public MDCoverageStructureListType createMDCoverageStructureListType() {
        return new MDCoverageStructureListType();
    }

    /**
     * Create an instance of {@link CDisplayCapTotalType }
     * 
     */
    public CDisplayCapTotalType createCDisplayCapTotalType() {
        return new CDisplayCapTotalType();
    }

    /**
     * Create an instance of {@link SysExposureIsUnitsType }
     * 
     */
    public SysExposureIsUnitsType createSysExposureIsUnitsType() {
        return new SysExposureIsUnitsType();
    }

    /**
     * Create an instance of {@link PRODUCERPHYSICALADDListType }
     * 
     */
    public PRODUCERPHYSICALADDListType createPRODUCERPHYSICALADDListType() {
        return new PRODUCERPHYSICALADDListType();
    }

    /**
     * Create an instance of {@link CSelectionLobFlagType }
     * 
     */
    public CSelectionLobFlagType createCSelectionLobFlagType() {
        return new CSelectionLobFlagType();
    }

    /**
     * Create an instance of {@link CDevFrmSchdledPrimaryType }
     * 
     */
    public CDevFrmSchdledPrimaryType createCDevFrmSchdledPrimaryType() {
        return new CDevFrmSchdledPrimaryType();
    }

    /**
     * Create an instance of {@link WrittenPremiumType }
     * 
     */
    public WrittenPremiumType createWrittenPremiumType() {
        return new WrittenPremiumType();
    }

    /**
     * Create an instance of {@link CAddr1TypeType }
     * 
     */
    public CAddr1TypeType createCAddr1TypeType() {
        return new CAddr1TypeType();
    }

    /**
     * Create an instance of {@link BookingStatusType }
     * 
     */
    public BookingStatusType createBookingStatusType() {
        return new BookingStatusType();
    }

    /**
     * Create an instance of {@link EffectiveDateType }
     * 
     */
    public EffectiveDateType createEffectiveDateType() {
        return new EffectiveDateType();
    }

    /**
     * Create an instance of {@link CCovCodeType }
     * 
     */
    public CCovCodeType createCCovCodeType() {
        return new CCovCodeType();
    }

    /**
     * Create an instance of {@link IsSubToFullyEarnType }
     * 
     */
    public IsSubToFullyEarnType createIsSubToFullyEarnType() {
        return new IsSubToFullyEarnType();
    }

    /**
     * Create an instance of {@link CHomeOfficeStateType }
     * 
     */
    public CHomeOfficeStateType createCHomeOfficeStateType() {
        return new CHomeOfficeStateType();
    }

    /**
     * Create an instance of {@link RulesetExecIdType }
     * 
     */
    public RulesetExecIdType createRulesetExecIdType() {
        return new RulesetExecIdType();
    }

    /**
     * Create an instance of {@link DateModifiedType }
     * 
     */
    public DateModifiedType createDateModifiedType() {
        return new DateModifiedType();
    }

    /**
     * Create an instance of {@link CInvalidAdrRsnType }
     * 
     */
    public CInvalidAdrRsnType createCInvalidAdrRsnType() {
        return new CInvalidAdrRsnType();
    }

    /**
     * Create an instance of {@link CStdLine2Type }
     * 
     */
    public CStdLine2Type createCStdLine2Type() {
        return new CStdLine2Type();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link LobCodeType }
     * 
     */
    public LobCodeType createLobCodeType() {
        return new LobCodeType();
    }

    /**
     * Create an instance of {@link PolicyFinancialListType }
     * 
     */
    public PolicyFinancialListType createPolicyFinancialListType() {
        return new PolicyFinancialListType();
    }

    /**
     * Create an instance of {@link ProducerListType }
     * 
     */
    public ProducerListType createProducerListType() {
        return new ProducerListType();
    }

    /**
     * Create an instance of {@link CustomPolicyNumberType }
     * 
     */
    public CustomPolicyNumberType createCustomPolicyNumberType() {
        return new CustomPolicyNumberType();
    }

    /**
     * Create an instance of {@link RenewalIndicatorType }
     * 
     */
    public RenewalIndicatorType createRenewalIndicatorType() {
        return new RenewalIndicatorType();
    }

    /**
     * Create an instance of {@link DisplayInstallmentIdType }
     * 
     */
    public DisplayInstallmentIdType createDisplayInstallmentIdType() {
        return new DisplayInstallmentIdType();
    }

    /**
     * Create an instance of {@link EntityStatusListType }
     * 
     */
    public EntityStatusListType createEntityStatusListType() {
        return new EntityStatusListType();
    }

    /**
     * Create an instance of {@link ProductCodeType }
     * 
     */
    public ProductCodeType createProductCodeType() {
        return new ProductCodeType();
    }

    /**
     * Create an instance of {@link MDRatingDetailsListType }
     * 
     */
    public MDRatingDetailsListType createMDRatingDetailsListType() {
        return new MDRatingDetailsListType();
    }

    /**
     * Create an instance of {@link CSicDescriptionType }
     * 
     */
    public CSicDescriptionType createCSicDescriptionType() {
        return new CSicDescriptionType();
    }

    /**
     * Create an instance of {@link CFullyEarnedOverrideType }
     * 
     */
    public CFullyEarnedOverrideType createCFullyEarnedOverrideType() {
        return new CFullyEarnedOverrideType();
    }

    /**
     * Create an instance of {@link COccurrOrClaimsMadeType }
     * 
     */
    public COccurrOrClaimsMadeType createCOccurrOrClaimsMadeType() {
        return new COccurrOrClaimsMadeType();
    }

    /**
     * Create an instance of {@link PayorAddress1Type }
     * 
     */
    public PayorAddress1Type createPayorAddress1Type() {
        return new PayorAddress1Type();
    }

    /**
     * Create an instance of {@link CTermDateType }
     * 
     */
    public CTermDateType createCTermDateType() {
        return new CTermDateType();
    }

    /**
     * Create an instance of {@link CCoverageCodeType }
     * 
     */
    public CCoverageCodeType createCCoverageCodeType() {
        return new CCoverageCodeType();
    }

    /**
     * Create an instance of {@link CStateDescOfDomicileType }
     * 
     */
    public CStateDescOfDomicileType createCStateDescOfDomicileType() {
        return new CStateDescOfDomicileType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link CPolIsoCounterType }
     * 
     */
    public CPolIsoCounterType createCPolIsoCounterType() {
        return new CPolIsoCounterType();
    }

    /**
     * Create an instance of {@link CFormTypeType }
     * 
     */
    public CFormTypeType createCFormTypeType() {
        return new CFormTypeType();
    }

    /**
     * Create an instance of {@link CDevFrmSchdledExcessType }
     * 
     */
    public CDevFrmSchdledExcessType createCDevFrmSchdledExcessType() {
        return new CDevFrmSchdledExcessType();
    }

    /**
     * Create an instance of {@link CommissionListType }
     * 
     */
    public CommissionListType createCommissionListType() {
        return new CommissionListType();
    }

    /**
     * Create an instance of {@link TransactionFactorType }
     * 
     */
    public TransactionFactorType createTransactionFactorType() {
        return new TransactionFactorType();
    }

    /**
     * Create an instance of {@link CHasLobTcType }
     * 
     */
    public CHasLobTcType createCHasLobTcType() {
        return new CHasLobTcType();
    }

    /**
     * Create an instance of {@link CCovSelRetroDateType }
     * 
     */
    public CCovSelRetroDateType createCCovSelRetroDateType() {
        return new CCovSelRetroDateType();
    }

    /**
     * Create an instance of {@link WaivedPremiumType }
     * 
     */
    public WaivedPremiumType createWaivedPremiumType() {
        return new WaivedPremiumType();
    }

    /**
     * Create an instance of {@link COfacCheckStatusMsgType }
     * 
     */
    public COfacCheckStatusMsgType createCOfacCheckStatusMsgType() {
        return new COfacCheckStatusMsgType();
    }

    /**
     * Create an instance of {@link AddressListType }
     * 
     */
    public AddressListType createAddressListType() {
        return new AddressListType();
    }

    /**
     * Create an instance of {@link PolicyReferenceType }
     * 
     */
    public PolicyReferenceType createPolicyReferenceType() {
        return new PolicyReferenceType();
    }

    /**
     * Create an instance of {@link ActionStatusType }
     * 
     */
    public ActionStatusType createActionStatusType() {
        return new ActionStatusType();
    }

    /**
     * Create an instance of {@link TransactionActionType }
     * 
     */
    public TransactionActionType createTransactionActionType() {
        return new TransactionActionType();
    }

    /**
     * Create an instance of {@link InsuredSearchCompleteType }
     * 
     */
    public InsuredSearchCompleteType createInsuredSearchCompleteType() {
        return new InsuredSearchCompleteType();
    }

    /**
     * Create an instance of {@link COfacCheckStatusType }
     * 
     */
    public COfacCheckStatusType createCOfacCheckStatusType() {
        return new COfacCheckStatusType();
    }

    /**
     * Create an instance of {@link UnderwriterCodeType }
     * 
     */
    public UnderwriterCodeType createUnderwriterCodeType() {
        return new UnderwriterCodeType();
    }

    /**
     * Create an instance of {@link TransDisplayNameType }
     * 
     */
    public TransDisplayNameType createTransDisplayNameType() {
        return new TransDisplayNameType();
    }

    /**
     * Create an instance of {@link BalanceToMinimumType }
     * 
     */
    public BalanceToMinimumType createBalanceToMinimumType() {
        return new BalanceToMinimumType();
    }

    /**
     * Create an instance of {@link ProductNameType }
     * 
     */
    public ProductNameType createProductNameType() {
        return new ProductNameType();
    }

    /**
     * Create an instance of {@link CIsoCodeType }
     * 
     */
    public CIsoCodeType createCIsoCodeType() {
        return new CIsoCodeType();
    }

    /**
     * Create an instance of {@link QBPolicyDynamicFormDataListType }
     * 
     */
    public QBPolicyDynamicFormDataListType createQBPolicyDynamicFormDataListType() {
        return new QBPolicyDynamicFormDataListType();
    }

    /**
     * Create an instance of {@link EMailType }
     * 
     */
    public EMailType createEMailType() {
        return new EMailType();
    }

    /**
     * Create an instance of {@link TotalTransSurchargeType }
     * 
     */
    public TotalTransSurchargeType createTotalTransSurchargeType() {
        return new TotalTransSurchargeType();
    }

    /**
     * Create an instance of {@link CHasLobFbType }
     * 
     */
    public CHasLobFbType createCHasLobFbType() {
        return new CHasLobFbType();
    }

    /**
     * Create an instance of {@link NewEntityReferenceType }
     * 
     */
    public NewEntityReferenceType createNewEntityReferenceType() {
        return new NewEntityReferenceType();
    }

    /**
     * Create an instance of {@link MDFinancialAnalysisType }
     * 
     */
    public MDFinancialAnalysisType createMDFinancialAnalysisType() {
        return new MDFinancialAnalysisType();
    }

    /**
     * Create an instance of {@link PaperTypeType }
     * 
     */
    public PaperTypeType createPaperTypeType() {
        return new PaperTypeType();
    }

    /**
     * Create an instance of {@link CExtReportingPeriodType }
     * 
     */
    public CExtReportingPeriodType createCExtReportingPeriodType() {
        return new CExtReportingPeriodType();
    }

    /**
     * Create an instance of {@link CUniqueKeyType }
     * 
     */
    public CUniqueKeyType createCUniqueKeyType() {
        return new CUniqueKeyType();
    }

    /**
     * Create an instance of {@link CExpirationDateFlagType }
     * 
     */
    public CExpirationDateFlagType createCExpirationDateFlagType() {
        return new CExpirationDateFlagType();
    }

    /**
     * Create an instance of {@link TransPremNotSubToAudType }
     * 
     */
    public TransPremNotSubToAudType createTransPremNotSubToAudType() {
        return new TransPremNotSubToAudType();
    }

    /**
     * Create an instance of {@link BusinessNameType }
     * 
     */
    public BusinessNameType createBusinessNameType() {
        return new BusinessNameType();
    }

    /**
     * Create an instance of {@link CExpirationDateType }
     * 
     */
    public CExpirationDateType createCExpirationDateType() {
        return new CExpirationDateType();
    }

    /**
     * Create an instance of {@link CRatingDetailsUkType }
     * 
     */
    public CRatingDetailsUkType createCRatingDetailsUkType() {
        return new CRatingDetailsUkType();
    }

    /**
     * Create an instance of {@link TransAccountingDateType }
     * 
     */
    public TransAccountingDateType createTransAccountingDateType() {
        return new TransAccountingDateType();
    }

    /**
     * Create an instance of {@link MDRiskModifierListType }
     * 
     */
    public MDRiskModifierListType createMDRiskModifierListType() {
        return new MDRiskModifierListType();
    }

    /**
     * Create an instance of {@link CCompanyType }
     * 
     */
    public CCompanyType createCCompanyType() {
        return new CCompanyType();
    }

    /**
     * Create an instance of {@link PRODUCERPHYSICALADDType }
     * 
     */
    public PRODUCERPHYSICALADDType createPRODUCERPHYSICALADDType() {
        return new PRODUCERPHYSICALADDType();
    }

    /**
     * Create an instance of {@link MasterRecordGidType }
     * 
     */
    public MasterRecordGidType createMasterRecordGidType() {
        return new MasterRecordGidType();
    }

    /**
     * Create an instance of {@link CompositeRatingType }
     * 
     */
    public CompositeRatingType createCompositeRatingType() {
        return new CompositeRatingType();
    }

    /**
     * Create an instance of {@link CRetroDateType }
     * 
     */
    public CRetroDateType createCRetroDateType() {
        return new CRetroDateType();
    }

    /**
     * Create an instance of {@link CStdLine1Type }
     * 
     */
    public CStdLine1Type createCStdLine1Type() {
        return new CStdLine1Type();
    }

    /**
     * Create an instance of {@link CAggregateLmtType }
     * 
     */
    public CAggregateLmtType createCAggregateLmtType() {
        return new CAggregateLmtType();
    }

    /**
     * Create an instance of {@link CCompClassCodeType }
     * 
     */
    public CCompClassCodeType createCCompClassCodeType() {
        return new CCompClassCodeType();
    }

    /**
     * Create an instance of {@link OrderCreditScoreType }
     * 
     */
    public OrderCreditScoreType createOrderCreditScoreType() {
        return new OrderCreditScoreType();
    }

    /**
     * Create an instance of {@link CPolicyTypeType }
     * 
     */
    public CPolicyTypeType createCPolicyTypeType() {
        return new CPolicyTypeType();
    }

    /**
     * Create an instance of {@link CCovSelOverPpDateType }
     * 
     */
    public CCovSelOverPpDateType createCCovSelOverPpDateType() {
        return new CCovSelOverPpDateType();
    }

    /**
     * Create an instance of {@link CPubQbeEquPremDispType }
     * 
     */
    public CPubQbeEquPremDispType createCPubQbeEquPremDispType() {
        return new CPubQbeEquPremDispType();
    }

    /**
     * Create an instance of {@link SurplusLinesType }
     * 
     */
    public SurplusLinesType createSurplusLinesType() {
        return new SurplusLinesType();
    }

    /**
     * Create an instance of {@link PayorStateType }
     * 
     */
    public PayorStateType createPayorStateType() {
        return new PayorStateType();
    }

    /**
     * Create an instance of {@link EntityStatusType }
     * 
     */
    public EntityStatusType createEntityStatusType() {
        return new EntityStatusType();
    }

    /**
     * Create an instance of {@link CExpoTypeOfMediaType }
     * 
     */
    public CExpoTypeOfMediaType createCExpoTypeOfMediaType() {
        return new CExpoTypeOfMediaType();
    }

    /**
     * Create an instance of {@link MediaLiabilityListType }
     * 
     */
    public MediaLiabilityListType createMediaLiabilityListType() {
        return new MediaLiabilityListType();
    }

    /**
     * Create an instance of {@link OrgEntityReferenceType }
     * 
     */
    public OrgEntityReferenceType createOrgEntityReferenceType() {
        return new OrgEntityReferenceType();
    }

    /**
     * Create an instance of {@link IsRewriteType }
     * 
     */
    public IsRewriteType createIsRewriteType() {
        return new IsRewriteType();
    }

    /**
     * Create an instance of {@link FormDateCreatedType }
     * 
     */
    public FormDateCreatedType createFormDateCreatedType() {
        return new FormDateCreatedType();
    }

    /**
     * Create an instance of {@link TotalFtermTaxesType }
     * 
     */
    public TotalFtermTaxesType createTotalFtermTaxesType() {
        return new TotalFtermTaxesType();
    }

    /**
     * Create an instance of {@link CCovProfAggLimitType }
     * 
     */
    public CCovProfAggLimitType createCCovProfAggLimitType() {
        return new CCovProfAggLimitType();
    }

    /**
     * Create an instance of {@link CLobSelLobTypeType }
     * 
     */
    public CLobSelLobTypeType createCLobSelLobTypeType() {
        return new CLobSelLobTypeType();
    }

    /**
     * Create an instance of {@link PayorAddress2Type }
     * 
     */
    public PayorAddress2Type createPayorAddress2Type() {
        return new PayorAddress2Type();
    }

    /**
     * Create an instance of {@link TotalFtermFeeType }
     * 
     */
    public TotalFtermFeeType createTotalFtermFeeType() {
        return new TotalFtermFeeType();
    }

    /**
     * Create an instance of {@link CHasLobFdType }
     * 
     */
    public CHasLobFdType createCHasLobFdType() {
        return new CHasLobFdType();
    }

    /**
     * Create an instance of {@link CountyType }
     * 
     */
    public CountyType createCountyType() {
        return new CountyType();
    }

    /**
     * Create an instance of {@link ValidPayOptionIdType }
     * 
     */
    public ValidPayOptionIdType createValidPayOptionIdType() {
        return new ValidPayOptionIdType();
    }

    /**
     * Create an instance of {@link FormEditiondateType }
     * 
     */
    public FormEditiondateType createFormEditiondateType() {
        return new FormEditiondateType();
    }

    /**
     * Create an instance of {@link ControlDateType }
     * 
     */
    public ControlDateType createControlDateType() {
        return new ControlDateType();
    }

    /**
     * Create an instance of {@link TotalSurchargeType }
     * 
     */
    public TotalSurchargeType createTotalSurchargeType() {
        return new TotalSurchargeType();
    }

    /**
     * Create an instance of {@link CRetentionType }
     * 
     */
    public CRetentionType createCRetentionType() {
        return new CRetentionType();
    }

    /**
     * Create an instance of {@link NameTypeType }
     * 
     */
    public NameTypeType createNameTypeType() {
        return new NameTypeType();
    }

    /**
     * Create an instance of {@link CCollectorMethodCodeType }
     * 
     */
    public CCollectorMethodCodeType createCCollectorMethodCodeType() {
        return new CCollectorMethodCodeType();
    }

    /**
     * Create an instance of {@link MDRiskCharacteristicsNonFinancialListType }
     * 
     */
    public MDRiskCharacteristicsNonFinancialListType createMDRiskCharacteristicsNonFinancialListType() {
        return new MDRiskCharacteristicsNonFinancialListType();
    }

    /**
     * Create an instance of {@link CIsOverrideDefaultsType }
     * 
     */
    public CIsOverrideDefaultsType createCIsOverrideDefaultsType() {
        return new CIsOverrideDefaultsType();
    }

    /**
     * Create an instance of {@link PolicyUnderwriterType }
     * 
     */
    public PolicyUnderwriterType createPolicyUnderwriterType() {
        return new PolicyUnderwriterType();
    }

    /**
     * Create an instance of {@link MDPremiumSummaryDetailListType }
     * 
     */
    public MDPremiumSummaryDetailListType createMDPremiumSummaryDetailListType() {
        return new MDPremiumSummaryDetailListType();
    }

    /**
     * Create an instance of {@link CustomPackVersionType }
     * 
     */
    public CustomPackVersionType createCustomPackVersionType() {
        return new CustomPackVersionType();
    }

    /**
     * Create an instance of {@link RateClickedType }
     * 
     */
    public RateClickedType createRateClickedType() {
        return new RateClickedType();
    }

    /**
     * Create an instance of {@link AnnualPremiumType }
     * 
     */
    public AnnualPremiumType createAnnualPremiumType() {
        return new AnnualPremiumType();
    }

    /**
     * Create an instance of {@link DisplayProducerCodeType }
     * 
     */
    public DisplayProducerCodeType createDisplayProducerCodeType() {
        return new DisplayProducerCodeType();
    }

    /**
     * Create an instance of {@link CSkipAddVerifyType }
     * 
     */
    public CSkipAddVerifyType createCSkipAddVerifyType() {
        return new CSkipAddVerifyType();
    }

    /**
     * Create an instance of {@link CPendingOrProceedDateType }
     * 
     */
    public CPendingOrProceedDateType createCPendingOrProceedDateType() {
        return new CPendingOrProceedDateType();
    }

    /**
     * Create an instance of {@link CHasLobMdType }
     * 
     */
    public CHasLobMdType createCHasLobMdType() {
        return new CHasLobMdType();
    }

    /**
     * Create an instance of {@link MDRatingDetailsType }
     * 
     */
    public MDRatingDetailsType createMDRatingDetailsType() {
        return new MDRatingDetailsType();
    }

    /**
     * Create an instance of {@link TransAccountingMonthType }
     * 
     */
    public TransAccountingMonthType createTransAccountingMonthType() {
        return new TransAccountingMonthType();
    }

    /**
     * Create an instance of {@link RulesetType }
     * 
     */
    public RulesetType createRulesetType() {
        return new RulesetType();
    }

    /**
     * Create an instance of {@link Phone1Type }
     * 
     */
    public Phone1Type createPhone1Type() {
        return new Phone1Type();
    }

    /**
     * Create an instance of {@link COwnershipTypeType }
     * 
     */
    public COwnershipTypeType createCOwnershipTypeType() {
        return new COwnershipTypeType();
    }

    /**
     * Create an instance of {@link MDHeaderInformationListType }
     * 
     */
    public MDHeaderInformationListType createMDHeaderInformationListType() {
        return new MDHeaderInformationListType();
    }

    /**
     * Create an instance of {@link DueDateType }
     * 
     */
    public DueDateType createDueDateType() {
        return new DueDateType();
    }

    /**
     * Create an instance of {@link COfficeNameType }
     * 
     */
    public COfficeNameType createCOfficeNameType() {
        return new COfficeNameType();
    }

    /**
     * Create an instance of {@link CRateItemType }
     * 
     */
    public CRateItemType createCRateItemType() {
        return new CRateItemType();
    }

    /**
     * Create an instance of {@link ChangedCommPremiumType }
     * 
     */
    public ChangedCommPremiumType createChangedCommPremiumType() {
        return new ChangedCommPremiumType();
    }

    /**
     * Create an instance of {@link MDUnderwritingCommentsListType }
     * 
     */
    public MDUnderwritingCommentsListType createMDUnderwritingCommentsListType() {
        return new MDUnderwritingCommentsListType();
    }

    /**
     * Create an instance of {@link CIsProdSelectedType }
     * 
     */
    public CIsProdSelectedType createCIsProdSelectedType() {
        return new CIsProdSelectedType();
    }

    /**
     * Create an instance of {@link SendDateType }
     * 
     */
    public SendDateType createSendDateType() {
        return new SendDateType();
    }

    /**
     * Create an instance of {@link OoseVoidIndicatorType }
     * 
     */
    public OoseVoidIndicatorType createOoseVoidIndicatorType() {
        return new OoseVoidIndicatorType();
    }

    /**
     * Create an instance of {@link CPhysicalAddressIdType }
     * 
     */
    public CPhysicalAddressIdType createCPhysicalAddressIdType() {
        return new CPhysicalAddressIdType();
    }

    /**
     * Create an instance of {@link CCharactersticsType }
     * 
     */
    public CCharactersticsType createCCharactersticsType() {
        return new CCharactersticsType();
    }

    /**
     * Create an instance of {@link COfficeTypeType }
     * 
     */
    public COfficeTypeType createCOfficeTypeType() {
        return new COfficeTypeType();
    }

    /**
     * Create an instance of {@link MLPLGeneralInformationType }
     * 
     */
    public MLPLGeneralInformationType createMLPLGeneralInformationType() {
        return new MLPLGeneralInformationType();
    }

    /**
     * Create an instance of {@link UnderWriterAddressListType }
     * 
     */
    public UnderWriterAddressListType createUnderWriterAddressListType() {
        return new UnderWriterAddressListType();
    }

    /**
     * Create an instance of {@link CDescriptionType }
     * 
     */
    public CDescriptionType createCDescriptionType() {
        return new CDescriptionType();
    }

    /**
     * Create an instance of {@link CommissionType }
     * 
     */
    public CommissionType createCommissionType() {
        return new CommissionType();
    }

    /**
     * Create an instance of {@link LobDescriptionType }
     * 
     */
    public LobDescriptionType createLobDescriptionType() {
        return new LobDescriptionType();
    }

    /**
     * Create an instance of {@link CCovStrDateResetType }
     * 
     */
    public CCovStrDateResetType createCCovStrDateResetType() {
        return new CCovStrDateResetType();
    }

    /**
     * Create an instance of {@link CCoverageTypeCodeType }
     * 
     */
    public CCoverageTypeCodeType createCCoverageTypeCodeType() {
        return new CCoverageTypeCodeType();
    }

    /**
     * Create an instance of {@link CRatingFormulaType }
     * 
     */
    public CRatingFormulaType createCRatingFormulaType() {
        return new CRatingFormulaType();
    }

    /**
     * Create an instance of {@link BillTypeType }
     * 
     */
    public BillTypeType createBillTypeType() {
        return new BillTypeType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link FormType }
     * 
     */
    public FormType createFormType() {
        return new FormType();
    }

    /**
     * Create an instance of {@link MicVersionType }
     * 
     */
    public MicVersionType createMicVersionType() {
        return new MicVersionType();
    }

    /**
     * Create an instance of {@link PayorTypeType }
     * 
     */
    public PayorTypeType createPayorTypeType() {
        return new PayorTypeType();
    }

    /**
     * Create an instance of {@link CLicenseCheckTimeType }
     * 
     */
    public CLicenseCheckTimeType createCLicenseCheckTimeType() {
        return new CLicenseCheckTimeType();
    }

    /**
     * Create an instance of {@link COverridePolEffDtType }
     * 
     */
    public COverridePolEffDtType createCOverridePolEffDtType() {
        return new COverridePolEffDtType();
    }

    /**
     * Create an instance of {@link CFullyEarnedType }
     * 
     */
    public CFullyEarnedType createCFullyEarnedType() {
        return new CFullyEarnedType();
    }

    /**
     * Create an instance of {@link SortOrderType }
     * 
     */
    public SortOrderType createSortOrderType() {
        return new SortOrderType();
    }

    /**
     * Create an instance of {@link CLimitType }
     * 
     */
    public CLimitType createCLimitType() {
        return new CLimitType();
    }

    /**
     * Create an instance of {@link COwnershipType }
     * 
     */
    public COwnershipType createCOwnershipType() {
        return new COwnershipType();
    }

    /**
     * Create an instance of {@link CCoverageTypeNameType }
     * 
     */
    public CCoverageTypeNameType createCCoverageTypeNameType() {
        return new CCoverageTypeNameType();
    }

    /**
     * Create an instance of {@link CCurrentFormulaType }
     * 
     */
    public CCurrentFormulaType createCCurrentFormulaType() {
        return new CCurrentFormulaType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link TransAccountingYearType }
     * 
     */
    public TransAccountingYearType createTransAccountingYearType() {
        return new TransAccountingYearType();
    }

    /**
     * Create an instance of {@link EntityTypeType }
     * 
     */
    public EntityTypeType createEntityTypeType() {
        return new EntityTypeType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link CSeparateOrSharedLmtType }
     * 
     */
    public CSeparateOrSharedLmtType createCSeparateOrSharedLmtType() {
        return new CSeparateOrSharedLmtType();
    }

    /**
     * Create an instance of {@link TransEffectiveDateType }
     * 
     */
    public TransEffectiveDateType createTransEffectiveDateType() {
        return new TransEffectiveDateType();
    }

    /**
     * Create an instance of {@link CErpPerOfAnnPremType }
     * 
     */
    public CErpPerOfAnnPremType createCErpPerOfAnnPremType() {
        return new CErpPerOfAnnPremType();
    }

    /**
     * Create an instance of {@link FeinPhoneRequiredType }
     * 
     */
    public FeinPhoneRequiredType createFeinPhoneRequiredType() {
        return new FeinPhoneRequiredType();
    }

    /**
     * Create an instance of {@link CStateOfDomicileType }
     * 
     */
    public CStateOfDomicileType createCStateOfDomicileType() {
        return new CStateOfDomicileType();
    }

    /**
     * Create an instance of {@link InstallmentListType }
     * 
     */
    public InstallmentListType createInstallmentListType() {
        return new InstallmentListType();
    }

    /**
     * Create an instance of {@link CommPlanCommType }
     * 
     */
    public CommPlanCommType createCommPlanCommType() {
        return new CommPlanCommType();
    }

    /**
     * Create an instance of {@link MLPLType }
     * 
     */
    public MLPLType createMLPLType() {
        return new MLPLType();
    }

    /**
     * Create an instance of {@link CCovSelectionLimitType }
     * 
     */
    public CCovSelectionLimitType createCCovSelectionLimitType() {
        return new CCovSelectionLimitType();
    }

    /**
     * Create an instance of {@link CEffectiveDateFlagType }
     * 
     */
    public CEffectiveDateFlagType createCEffectiveDateFlagType() {
        return new CEffectiveDateFlagType();
    }

    /**
     * Create an instance of {@link StateCodeType }
     * 
     */
    public StateCodeType createStateCodeType() {
        return new StateCodeType();
    }

    /**
     * Create an instance of {@link FormListType }
     * 
     */
    public FormListType createFormListType() {
        return new FormListType();
    }

    /**
     * Create an instance of {@link TotalAnnualTaxType }
     * 
     */
    public TotalAnnualTaxType createTotalAnnualTaxType() {
        return new TotalAnnualTaxType();
    }

    /**
     * Create an instance of {@link SubjectivitiesListType }
     * 
     */
    public SubjectivitiesListType createSubjectivitiesListType() {
        return new SubjectivitiesListType();
    }

    /**
     * Create an instance of {@link CCreditTermsType }
     * 
     */
    public CCreditTermsType createCCreditTermsType() {
        return new CCreditTermsType();
    }

    /**
     * Create an instance of {@link TotalAnnualColFeeType }
     * 
     */
    public TotalAnnualColFeeType createTotalAnnualColFeeType() {
        return new TotalAnnualColFeeType();
    }

    /**
     * Create an instance of {@link IsCommPlanTiredType }
     * 
     */
    public IsCommPlanTiredType createIsCommPlanTiredType() {
        return new IsCommPlanTiredType();
    }

    /**
     * Create an instance of {@link CHasLobMlType }
     * 
     */
    public CHasLobMlType createCHasLobMlType() {
        return new CHasLobMlType();
    }

    /**
     * Create an instance of {@link CStdCityType }
     * 
     */
    public CStdCityType createCStdCityType() {
        return new CStdCityType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link CInsNamOfacCheckTimeType }
     * 
     */
    public CInsNamOfacCheckTimeType createCInsNamOfacCheckTimeType() {
        return new CInsNamOfacCheckTimeType();
    }

    /**
     * Create an instance of {@link CTypeOfMediaType }
     * 
     */
    public CTypeOfMediaType createCTypeOfMediaType() {
        return new CTypeOfMediaType();
    }

    /**
     * Create an instance of {@link CNyftzClassCodeType }
     * 
     */
    public CNyftzClassCodeType createCNyftzClassCodeType() {
        return new CNyftzClassCodeType();
    }

    /**
     * Create an instance of {@link CompositeRateIncludedType }
     * 
     */
    public CompositeRateIncludedType createCompositeRateIncludedType() {
        return new CompositeRateIncludedType();
    }

    /**
     * Create an instance of {@link CWebsiteType }
     * 
     */
    public CWebsiteType createCWebsiteType() {
        return new CWebsiteType();
    }

    /**
     * Create an instance of {@link SourceSystemType }
     * 
     */
    public SourceSystemType createSourceSystemType() {
        return new SourceSystemType();
    }

    /**
     * Create an instance of {@link CCovSelectionRetType }
     * 
     */
    public CCovSelectionRetType createCCovSelectionRetType() {
        return new CCovSelectionRetType();
    }

    /**
     * Create an instance of {@link FormnumberType }
     * 
     */
    public FormnumberType createFormnumberType() {
        return new FormnumberType();
    }

    /**
     * Create an instance of {@link RulesetIdType }
     * 
     */
    public RulesetIdType createRulesetIdType() {
        return new RulesetIdType();
    }

    /**
     * Create an instance of {@link CCoveragePartNameType }
     * 
     */
    public CCoveragePartNameType createCCoveragePartNameType() {
        return new CCoveragePartNameType();
    }

    /**
     * Create an instance of {@link CIsBrokerProducerSameType }
     * 
     */
    public CIsBrokerProducerSameType createCIsBrokerProducerSameType() {
        return new CIsBrokerProducerSameType();
    }

    /**
     * Create an instance of {@link MDSignificantTermsAndConditionAdditonalCoverageListType }
     * 
     */
    public MDSignificantTermsAndConditionAdditonalCoverageListType createMDSignificantTermsAndConditionAdditonalCoverageListType() {
        return new MDSignificantTermsAndConditionAdditonalCoverageListType();
    }

    /**
     * Create an instance of {@link CStdZipCodeType }
     * 
     */
    public CStdZipCodeType createCStdZipCodeType() {
        return new CStdZipCodeType();
    }

    /**
     * Create an instance of {@link BinderFlagType }
     * 
     */
    public BinderFlagType createBinderFlagType() {
        return new BinderFlagType();
    }

    /**
     * Create an instance of {@link MLPLLinesOfBusinessListType }
     * 
     */
    public MLPLLinesOfBusinessListType createMLPLLinesOfBusinessListType() {
        return new MLPLLinesOfBusinessListType();
    }

    /**
     * Create an instance of {@link RiskStateStatCodeType }
     * 
     */
    public RiskStateStatCodeType createRiskStateStatCodeType() {
        return new RiskStateStatCodeType();
    }

    /**
     * Create an instance of {@link CHomeOfficeZipType }
     * 
     */
    public CHomeOfficeZipType createCHomeOfficeZipType() {
        return new CHomeOfficeZipType();
    }

    /**
     * Create an instance of {@link CHasLobCcType }
     * 
     */
    public CHasLobCcType createCHasLobCcType() {
        return new CHasLobCcType();
    }

    /**
     * Create an instance of {@link CCurrentType }
     * 
     */
    public CCurrentType createCCurrentType() {
        return new CCurrentType();
    }

    /**
     * Create an instance of {@link CManualPremDispType }
     * 
     */
    public CManualPremDispType createCManualPremDispType() {
        return new CManualPremDispType();
    }

    /**
     * Create an instance of {@link CNaicDescriptionType }
     * 
     */
    public CNaicDescriptionType createCNaicDescriptionType() {
        return new CNaicDescriptionType();
    }

    /**
     * Create an instance of {@link OnDemandReorderType }
     * 
     */
    public OnDemandReorderType createOnDemandReorderType() {
        return new OnDemandReorderType();
    }

    /**
     * Create an instance of {@link Line1Type }
     * 
     */
    public Line1Type createLine1Type() {
        return new Line1Type();
    }

    /**
     * Create an instance of {@link RankType }
     * 
     */
    public RankType createRankType() {
        return new RankType();
    }

    /**
     * Create an instance of {@link CFinalPremiumType }
     * 
     */
    public CFinalPremiumType createCFinalPremiumType() {
        return new CFinalPremiumType();
    }

    /**
     * Create an instance of {@link MLPLLinesOfBusinessType }
     * 
     */
    public MLPLLinesOfBusinessType createMLPLLinesOfBusinessType() {
        return new MLPLLinesOfBusinessType();
    }

    /**
     * Create an instance of {@link OldEntityReferenceType }
     * 
     */
    public OldEntityReferenceType createOldEntityReferenceType() {
        return new OldEntityReferenceType();
    }

    /**
     * Create an instance of {@link UnderwriterContactListType }
     * 
     */
    public UnderwriterContactListType createUnderwriterContactListType() {
        return new UnderwriterContactListType();
    }

    /**
     * Create an instance of {@link CStateCodeOfDomicileType }
     * 
     */
    public CStateCodeOfDomicileType createCStateCodeOfDomicileType() {
        return new CStateCodeOfDomicileType();
    }

    /**
     * Create an instance of {@link MDUnderwritingCommentsType }
     * 
     */
    public MDUnderwritingCommentsType createMDUnderwritingCommentsType() {
        return new MDUnderwritingCommentsType();
    }

    /**
     * Create an instance of {@link PayorNameType }
     * 
     */
    public PayorNameType createPayorNameType() {
        return new PayorNameType();
    }

    /**
     * Create an instance of {@link DirectBillIndicatorType }
     * 
     */
    public DirectBillIndicatorType createDirectBillIndicatorType() {
        return new DirectBillIndicatorType();
    }

    /**
     * Create an instance of {@link InsuredType }
     * 
     */
    public InsuredType createInsuredType() {
        return new InsuredType();
    }

    /**
     * Create an instance of {@link ProductVersionType }
     * 
     */
    public ProductVersionType createProductVersionType() {
        return new ProductVersionType();
    }

    /**
     * Create an instance of {@link CRatingDetailTwistyType }
     * 
     */
    public CRatingDetailTwistyType createCRatingDetailTwistyType() {
        return new CRatingDetailTwistyType();
    }

    /**
     * Create an instance of {@link CFullyEarnedSumType }
     * 
     */
    public CFullyEarnedSumType createCFullyEarnedSumType() {
        return new CFullyEarnedSumType();
    }

    /**
     * Create an instance of {@link CSortOrderType }
     * 
     */
    public CSortOrderType createCSortOrderType() {
        return new CSortOrderType();
    }

    /**
     * Create an instance of {@link CommPlanIdType }
     * 
     */
    public CommPlanIdType createCommPlanIdType() {
        return new CommPlanIdType();
    }

    /**
     * Create an instance of {@link CRiskCategoryType }
     * 
     */
    public CRiskCategoryType createCRiskCategoryType() {
        return new CRiskCategoryType();
    }

    /**
     * Create an instance of {@link CPhoneTypeType }
     * 
     */
    public CPhoneTypeType createCPhoneTypeType() {
        return new CPhoneTypeType();
    }

    /**
     * Create an instance of {@link DisplayPolicyNumberType }
     * 
     */
    public DisplayPolicyNumberType createDisplayPolicyNumberType() {
        return new DisplayPolicyNumberType();
    }

    /**
     * Create an instance of {@link IsCovManuallyRatedType }
     * 
     */
    public IsCovManuallyRatedType createIsCovManuallyRatedType() {
        return new IsCovManuallyRatedType();
    }

    /**
     * Create an instance of {@link CEmailType }
     * 
     */
    public CEmailType createCEmailType() {
        return new CEmailType();
    }

    /**
     * Create an instance of {@link QuoteLetterUWCommentListType }
     * 
     */
    public QuoteLetterUWCommentListType createQuoteLetterUWCommentListType() {
        return new QuoteLetterUWCommentListType();
    }

    /**
     * Create an instance of {@link CCovStructTwistyType }
     * 
     */
    public CCovStructTwistyType createCCovStructTwistyType() {
        return new CCovStructTwistyType();
    }

    /**
     * Create an instance of {@link NetCommissionType }
     * 
     */
    public NetCommissionType createNetCommissionType() {
        return new NetCommissionType();
    }

    /**
     * Create an instance of {@link CharactersticsMinMaxDetailsType }
     * 
     */
    public CharactersticsMinMaxDetailsType createCharactersticsMinMaxDetailsType() {
        return new CharactersticsMinMaxDetailsType();
    }

    /**
     * Create an instance of {@link RulesetListType }
     * 
     */
    public RulesetListType createRulesetListType() {
        return new RulesetListType();
    }

    /**
     * Create an instance of {@link UserDeleteOverrideType }
     * 
     */
    public UserDeleteOverrideType createUserDeleteOverrideType() {
        return new UserDeleteOverrideType();
    }

    /**
     * Create an instance of {@link CAttentionType }
     * 
     */
    public CAttentionType createCAttentionType() {
        return new CAttentionType();
    }

    /**
     * Create an instance of {@link CanWaivePremiumType }
     * 
     */
    public CanWaivePremiumType createCanWaivePremiumType() {
        return new CanWaivePremiumType();
    }

    /**
     * Create an instance of {@link ManualAttachType }
     * 
     */
    public ManualAttachType createManualAttachType() {
        return new ManualAttachType();
    }

    /**
     * Create an instance of {@link Line2Type }
     * 
     */
    public Line2Type createLine2Type() {
        return new Line2Type();
    }

    /**
     * Create an instance of {@link CCharMinMaxTwistyType }
     * 
     */
    public CCharMinMaxTwistyType createCCharMinMaxTwistyType() {
        return new CCharMinMaxTwistyType();
    }

    /**
     * Create an instance of {@link MDCoverageStructureType }
     * 
     */
    public MDCoverageStructureType createMDCoverageStructureType() {
        return new MDCoverageStructureType();
    }

    /**
     * Create an instance of {@link QuotePolicyType }
     * 
     */
    public QuotePolicyType createQuotePolicyType() {
        return new QuotePolicyType();
    }

    /**
     * Create an instance of {@link MediaLiabilityType }
     * 
     */
    public MediaLiabilityType createMediaLiabilityType() {
        return new MediaLiabilityType();
    }

    /**
     * Create an instance of {@link TransactionPremiumType }
     * 
     */
    public TransactionPremiumType createTransactionPremiumType() {
        return new TransactionPremiumType();
    }

    /**
     * Create an instance of {@link CAddr2TypeType }
     * 
     */
    public CAddr2TypeType createCAddr2TypeType() {
        return new CAddr2TypeType();
    }

    /**
     * Create an instance of {@link CManualPremType }
     * 
     */
    public CManualPremType createCManualPremType() {
        return new CManualPremType();
    }

    /**
     * Create an instance of {@link CHomeOfficeCityType }
     * 
     */
    public CHomeOfficeCityType createCHomeOfficeCityType() {
        return new CHomeOfficeCityType();
    }

    /**
     * Create an instance of {@link CLimitTypeType }
     * 
     */
    public CLimitTypeType createCLimitTypeType() {
        return new CLimitTypeType();
    }

    /**
     * Create an instance of {@link CommissionablePremiumType }
     * 
     */
    public CommissionablePremiumType createCommissionablePremiumType() {
        return new CommissionablePremiumType();
    }

    /**
     * Create an instance of {@link CSelectedLobRetentionType }
     * 
     */
    public CSelectedLobRetentionType createCSelectedLobRetentionType() {
        return new CSelectedLobRetentionType();
    }

    /**
     * Create an instance of {@link CSeqType }
     * 
     */
    public CSeqType createCSeqType() {
        return new CSeqType();
    }

    /**
     * Create an instance of {@link CDevFrmSchPrimDispType }
     * 
     */
    public CDevFrmSchPrimDispType createCDevFrmSchPrimDispType() {
        return new CDevFrmSchPrimDispType();
    }

    /**
     * Create an instance of {@link CMinFactorType }
     * 
     */
    public CMinFactorType createCMinFactorType() {
        return new CMinFactorType();
    }

    /**
     * Create an instance of {@link CLimitModifyFlagType }
     * 
     */
    public CLimitModifyFlagType createCLimitModifyFlagType() {
        return new CLimitModifyFlagType();
    }

    /**
     * Create an instance of {@link CommPlanDescType }
     * 
     */
    public CommPlanDescType createCommPlanDescType() {
        return new CommPlanDescType();
    }

    /**
     * Create an instance of {@link CLobDateDesForResetType }
     * 
     */
    public CLobDateDesForResetType createCLobDateDesForResetType() {
        return new CLobDateDesForResetType();
    }

    /**
     * Create an instance of {@link CCovAggLimitType }
     * 
     */
    public CCovAggLimitType createCCovAggLimitType() {
        return new CCovAggLimitType();
    }

    /**
     * Create an instance of {@link CDesType }
     * 
     */
    public CDesType createCDesType() {
        return new CDesType();
    }

    /**
     * Create an instance of {@link CCoveragePartCodeType }
     * 
     */
    public CCoveragePartCodeType createCCoveragePartCodeType() {
        return new CCoveragePartCodeType();
    }

    /**
     * Create an instance of {@link NextGenAuditedType }
     * 
     */
    public NextGenAuditedType createNextGenAuditedType() {
        return new NextGenAuditedType();
    }

    /**
     * Create an instance of {@link RcFailureCancelType }
     * 
     */
    public RcFailureCancelType createRcFailureCancelType() {
        return new RcFailureCancelType();
    }

    /**
     * Create an instance of {@link FullTermPremiumType }
     * 
     */
    public FullTermPremiumType createFullTermPremiumType() {
        return new FullTermPremiumType();
    }

    /**
     * Create an instance of {@link DbNumberType }
     * 
     */
    public DbNumberType createDbNumberType() {
        return new DbNumberType();
    }

    /**
     * Create an instance of {@link InsuredTypeCodeType }
     * 
     */
    public InsuredTypeCodeType createInsuredTypeCodeType() {
        return new InsuredTypeCodeType();
    }

    /**
     * Create an instance of {@link ProducerCodeType }
     * 
     */
    public ProducerCodeType createProducerCodeType() {
        return new ProducerCodeType();
    }

    /**
     * Create an instance of {@link MDExposureInformationType }
     * 
     */
    public MDExposureInformationType createMDExposureInformationType() {
        return new MDExposureInformationType();
    }

    /**
     * Create an instance of {@link PolicyNumberType }
     * 
     */
    public PolicyNumberType createPolicyNumberType() {
        return new PolicyNumberType();
    }

    /**
     * Create an instance of {@link LobIncludedType }
     * 
     */
    public LobIncludedType createLobIncludedType() {
        return new LobIncludedType();
    }

    /**
     * Create an instance of {@link CPublicQbeEquPremType }
     * 
     */
    public CPublicQbeEquPremType createCPublicQbeEquPremType() {
        return new CPublicQbeEquPremType();
    }

    /**
     * Create an instance of {@link CHasLobPnType }
     * 
     */
    public CHasLobPnType createCHasLobPnType() {
        return new CHasLobPnType();
    }

    /**
     * Create an instance of {@link QuoteLetterUWCommentType }
     * 
     */
    public QuoteLetterUWCommentType createQuoteLetterUWCommentType() {
        return new QuoteLetterUWCommentType();
    }

    /**
     * Create an instance of {@link MDScheduleRatingListType }
     * 
     */
    public MDScheduleRatingListType createMDScheduleRatingListType() {
        return new MDScheduleRatingListType();
    }

    /**
     * Create an instance of {@link CIsBrokerSameProducerType }
     * 
     */
    public CIsBrokerSameProducerType createCIsBrokerSameProducerType() {
        return new CIsBrokerSameProducerType();
    }

    /**
     * Create an instance of {@link RenewalCounterType }
     * 
     */
    public RenewalCounterType createRenewalCounterType() {
        return new RenewalCounterType();
    }

    /**
     * Create an instance of {@link RiskStateType }
     * 
     */
    public RiskStateType createRiskStateType() {
        return new RiskStateType();
    }

    /**
     * Create an instance of {@link RenewalCounter2Type }
     * 
     */
    public RenewalCounter2Type createRenewalCounter2Type() {
        return new RenewalCounter2Type();
    }

    /**
     * Create an instance of {@link UnderwriterNameType }
     * 
     */
    public UnderwriterNameType createUnderwriterNameType() {
        return new UnderwriterNameType();
    }

    /**
     * Create an instance of {@link CRiskModifierTypeType }
     * 
     */
    public CRiskModifierTypeType createCRiskModifierTypeType() {
        return new CRiskModifierTypeType();
    }

    /**
     * Create an instance of {@link CExposureInfoType }
     * 
     */
    public CExposureInfoType createCExposureInfoType() {
        return new CExposureInfoType();
    }

    /**
     * Create an instance of {@link CPrsDetailTwistyType }
     * 
     */
    public CPrsDetailTwistyType createCPrsDetailTwistyType() {
        return new CPrsDetailTwistyType();
    }

    /**
     * Create an instance of {@link FormDateModifiedType }
     * 
     */
    public FormDateModifiedType createFormDateModifiedType() {
        return new FormDateModifiedType();
    }

    /**
     * Create an instance of {@link CLobCodeType }
     * 
     */
    public CLobCodeType createCLobCodeType() {
        return new CLobCodeType();
    }

    /**
     * Create an instance of {@link CStdCountryType }
     * 
     */
    public CStdCountryType createCStdCountryType() {
        return new CStdCountryType();
    }

    /**
     * Create an instance of {@link UserRemarksType }
     * 
     */
    public UserRemarksType createUserRemarksType() {
        return new UserRemarksType();
    }

    /**
     * Create an instance of {@link CAslobType }
     * 
     */
    public CAslobType createCAslobType() {
        return new CAslobType();
    }

    /**
     * Create an instance of {@link CSubLineCodeType }
     * 
     */
    public CSubLineCodeType createCSubLineCodeType() {
        return new CSubLineCodeType();
    }

    /**
     * Create an instance of {@link UserModifiedType }
     * 
     */
    public UserModifiedType createUserModifiedType() {
        return new UserModifiedType();
    }

    /**
     * Create an instance of {@link CHasLobFiType }
     * 
     */
    public CHasLobFiType createCHasLobFiType() {
        return new CHasLobFiType();
    }

    /**
     * Create an instance of {@link TransactionCodeType }
     * 
     */
    public TransactionCodeType createTransactionCodeType() {
        return new TransactionCodeType();
    }

    /**
     * Create an instance of {@link InsuredTypeType }
     * 
     */
    public InsuredTypeType createInsuredTypeType() {
        return new InsuredTypeType();
    }

    /**
     * Create an instance of {@link MDScheduleRatingType }
     * 
     */
    public MDScheduleRatingType createMDScheduleRatingType() {
        return new MDScheduleRatingType();
    }

    /**
     * Create an instance of {@link CompanyCodeType }
     * 
     */
    public CompanyCodeType createCompanyCodeType() {
        return new CompanyCodeType();
    }

    /**
     * Create an instance of {@link RetainBtmFltEndrType }
     * 
     */
    public RetainBtmFltEndrType createRetainBtmFltEndrType() {
        return new RetainBtmFltEndrType();
    }

    /**
     * Create an instance of {@link RatingDetailsType }
     * 
     */
    public RatingDetailsType createRatingDetailsType() {
        return new RatingDetailsType();
    }

    /**
     * Create an instance of {@link NaicsCodeType }
     * 
     */
    public NaicsCodeType createNaicsCodeType() {
        return new NaicsCodeType();
    }

    /**
     * Create an instance of {@link CExposureBaseType }
     * 
     */
    public CExposureBaseType createCExposureBaseType() {
        return new CExposureBaseType();
    }

    /**
     * Create an instance of {@link MLPLGeneralInformationListType }
     * 
     */
    public MLPLGeneralInformationListType createMLPLGeneralInformationListType() {
        return new MLPLGeneralInformationListType();
    }

    /**
     * Create an instance of {@link PrimaryType }
     * 
     */
    public PrimaryType createPrimaryType() {
        return new PrimaryType();
    }

    /**
     * Create an instance of {@link CoverageStructureDetailsListType }
     * 
     */
    public CoverageStructureDetailsListType createCoverageStructureDetailsListType() {
        return new CoverageStructureDetailsListType();
    }

    /**
     * Create an instance of {@link AuditIncludedType }
     * 
     */
    public AuditIncludedType createAuditIncludedType() {
        return new AuditIncludedType();
    }

    /**
     * Create an instance of {@link CNyftzType }
     * 
     */
    public CNyftzType createCNyftzType() {
        return new CNyftzType();
    }

    /**
     * Create an instance of {@link MDFinancialAnalysisListType }
     * 
     */
    public MDFinancialAnalysisListType createMDFinancialAnalysisListType() {
        return new MDFinancialAnalysisListType();
    }

    /**
     * Create an instance of {@link IsCovProratedType }
     * 
     */
    public IsCovProratedType createIsCovProratedType() {
        return new IsCovProratedType();
    }

    /**
     * Create an instance of {@link PaymentPlanCodeType }
     * 
     */
    public PaymentPlanCodeType createPaymentPlanCodeType() {
        return new PaymentPlanCodeType();
    }

    /**
     * Create an instance of {@link CResetDefaultsOnDateType }
     * 
     */
    public CResetDefaultsOnDateType createCResetDefaultsOnDateType() {
        return new CResetDefaultsOnDateType();
    }

    /**
     * Create an instance of {@link ExpirationDateType }
     * 
     */
    public ExpirationDateType createExpirationDateType() {
        return new ExpirationDateType();
    }

    /**
     * Create an instance of {@link ContactListType }
     * 
     */
    public ContactListType createContactListType() {
        return new ContactListType();
    }

    /**
     * Create an instance of {@link CRiskCharDateResetType }
     * 
     */
    public CRiskCharDateResetType createCRiskCharDateResetType() {
        return new CRiskCharDateResetType();
    }

    /**
     * Create an instance of {@link ProducerType }
     * 
     */
    public ProducerType createProducerType() {
        return new ProducerType();
    }

    /**
     * Create an instance of {@link ChangedPremiumType }
     * 
     */
    public ChangedPremiumType createChangedPremiumType() {
        return new ChangedPremiumType();
    }

    /**
     * Create an instance of {@link CHasLobDoType }
     * 
     */
    public CHasLobDoType createCHasLobDoType() {
        return new CHasLobDoType();
    }

    /**
     * Create an instance of {@link CPresidentNameType }
     * 
     */
    public CPresidentNameType createCPresidentNameType() {
        return new CPresidentNameType();
    }

    /**
     * Create an instance of {@link CStdStateCodeType }
     * 
     */
    public CStdStateCodeType createCStdStateCodeType() {
        return new CStdStateCodeType();
    }

    /**
     * Create an instance of {@link MDExposureInformationListType }
     * 
     */
    public MDExposureInformationListType createMDExposureInformationListType() {
        return new MDExposureInformationListType();
    }

    /**
     * Create an instance of {@link MDRiskModifierType }
     * 
     */
    public MDRiskModifierType createMDRiskModifierType() {
        return new MDRiskModifierType();
    }

    /**
     * Create an instance of {@link CRiskCharacteristicsUkType }
     * 
     */
    public CRiskCharacteristicsUkType createCRiskCharacteristicsUkType() {
        return new CRiskCharacteristicsUkType();
    }

    /**
     * Create an instance of {@link CLobPaperTypeType }
     * 
     */
    public CLobPaperTypeType createCLobPaperTypeType() {
        return new CLobPaperTypeType();
    }

    /**
     * Create an instance of {@link CDateIncorporatedType }
     * 
     */
    public CDateIncorporatedType createCDateIncorporatedType() {
        return new CDateIncorporatedType();
    }

    /**
     * Create an instance of {@link TotalAnnualSurchargeType }
     * 
     */
    public TotalAnnualSurchargeType createTotalAnnualSurchargeType() {
        return new TotalAnnualSurchargeType();
    }

    /**
     * Create an instance of {@link WaivePremiumType }
     * 
     */
    public WaivePremiumType createWaivePremiumType() {
        return new WaivePremiumType();
    }

    /**
     * Create an instance of {@link UnderWriterAddressType }
     * 
     */
    public UnderWriterAddressType createUnderWriterAddressType() {
        return new UnderWriterAddressType();
    }

    /**
     * Create an instance of {@link UnderwriterContactType }
     * 
     */
    public UnderwriterContactType createUnderwriterContactType() {
        return new UnderwriterContactType();
    }

    /**
     * Create an instance of {@link CTotalType }
     * 
     */
    public CTotalType createCTotalType() {
        return new CTotalType();
    }

    /**
     * Create an instance of {@link CSecretaryNameType }
     * 
     */
    public CSecretaryNameType createCSecretaryNameType() {
        return new CSecretaryNameType();
    }

    /**
     * Create an instance of {@link CPrimaryCovForRateType }
     * 
     */
    public CPrimaryCovForRateType createCPrimaryCovForRateType() {
        return new CPrimaryCovForRateType();
    }

    /**
     * Create an instance of {@link CRatedPremDispType }
     * 
     */
    public CRatedPremDispType createCRatedPremDispType() {
        return new CRatedPremDispType();
    }

    /**
     * Create an instance of {@link CoveragePartReferenceType }
     * 
     */
    public CoveragePartReferenceType createCoveragePartReferenceType() {
        return new CoveragePartReferenceType();
    }

    /**
     * Create an instance of {@link IsRebindType }
     * 
     */
    public IsRebindType createIsRebindType() {
        return new IsRebindType();
    }

    /**
     * Create an instance of {@link CDisplayTotalType }
     * 
     */
    public CDisplayTotalType createCDisplayTotalType() {
        return new CDisplayTotalType();
    }

    /**
     * Create an instance of {@link NewEntityTypeType }
     * 
     */
    public NewEntityTypeType createNewEntityTypeType() {
        return new NewEntityTypeType();
    }

    /**
     * Create an instance of {@link ActionDescType }
     * 
     */
    public ActionDescType createActionDescType() {
        return new ActionDescType();
    }

    /**
     * Create an instance of {@link CMlplPolicyTypeType }
     * 
     */
    public CMlplPolicyTypeType createCMlplPolicyTypeType() {
        return new CMlplPolicyTypeType();
    }

    /**
     * Create an instance of {@link PolicyQuoteIndicatorType }
     * 
     */
    public PolicyQuoteIndicatorType createPolicyQuoteIndicatorType() {
        return new PolicyQuoteIndicatorType();
    }

    /**
     * Create an instance of {@link CAgencyPhoneType }
     * 
     */
    public CAgencyPhoneType createCAgencyPhoneType() {
        return new CAgencyPhoneType();
    }

    /**
     * Create an instance of {@link MDHeaderInformationType }
     * 
     */
    public MDHeaderInformationType createMDHeaderInformationType() {
        return new MDHeaderInformationType();
    }

    /**
     * Create an instance of {@link CCoverageType }
     * 
     */
    public CCoverageType createCCoverageType() {
        return new CCoverageType();
    }

    /**
     * Create an instance of {@link CRatingFunctionType }
     * 
     */
    public CRatingFunctionType createCRatingFunctionType() {
        return new CRatingFunctionType();
    }

    /**
     * Create an instance of {@link CProfAggLmtType }
     * 
     */
    public CProfAggLmtType createCProfAggLmtType() {
        return new CProfAggLmtType();
    }

    /**
     * Create an instance of {@link CExpoOccuClaimsMadeType }
     * 
     */
    public CExpoOccuClaimsMadeType createCExpoOccuClaimsMadeType() {
        return new CExpoOccuClaimsMadeType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link QuoteUWCommentsListType }
     * 
     */
    public QuoteUWCommentsListType createQuoteUWCommentsListType() {
        return new QuoteUWCommentsListType();
    }

    /**
     * Create an instance of {@link CContactCodeType }
     * 
     */
    public CContactCodeType createCContactCodeType() {
        return new CContactCodeType();
    }

    /**
     * Create an instance of {@link CCappedTotalType }
     * 
     */
    public CCappedTotalType createCCappedTotalType() {
        return new CCappedTotalType();
    }

    /**
     * Create an instance of {@link CFormTypeFlagType }
     * 
     */
    public CFormTypeFlagType createCFormTypeFlagType() {
        return new CFormTypeFlagType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuotePolicyListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuotePolicyList")
    public JAXBElement<QuotePolicyListType> createQuotePolicyList(QuotePolicyListType value) {
        return new JAXBElement<QuotePolicyListType>(_QuotePolicyList_QNAME, QuotePolicyListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserModifiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserModified", scope = CommissionType.class)
    public JAXBElement<UserModifiedType> createCommissionTypeUserModified(UserModifiedType value) {
        return new JAXBElement<UserModifiedType>(_CommissionTypeUserModified_QNAME, UserModifiedType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommPlanCommType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommPlanComm", scope = CommissionType.class)
    public JAXBElement<CommPlanCommType> createCommissionTypeCommPlanComm(CommPlanCommType value) {
        return new JAXBElement<CommPlanCommType>(_CommissionTypeCommPlanComm_QNAME, CommPlanCommType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommPlanDescType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommPlanDesc", scope = CommissionType.class)
    public JAXBElement<CommPlanDescType> createCommissionTypeCommPlanDesc(CommPlanDescType value) {
        return new JAXBElement<CommPlanDescType>(_CommissionTypeCommPlanDesc_QNAME, CommPlanDescType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserCreatedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserCreated", scope = CommissionType.class)
    public JAXBElement<UserCreatedType> createCommissionTypeUserCreated(UserCreatedType value) {
        return new JAXBElement<UserCreatedType>(_CommissionTypeUserCreated_QNAME, UserCreatedType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommPlanNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommPlanName", scope = CommissionType.class)
    public JAXBElement<CommPlanNameType> createCommissionTypeCommPlanName(CommPlanNameType value) {
        return new JAXBElement<CommPlanNameType>(_CommissionTypeCommPlanName_QNAME, CommPlanNameType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Commission", scope = CommissionType.class)
    public JAXBElement<CommissionType> createCommissionTypeCommission(CommissionType value) {
        return new JAXBElement<CommissionType>(_CommissionTypeCommission_QNAME, CommissionType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateCreatedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateCreated", scope = CommissionType.class)
    public JAXBElement<DateCreatedType> createCommissionTypeDateCreated(DateCreatedType value) {
        return new JAXBElement<DateCreatedType>(_CommissionTypeDateCreated_QNAME, DateCreatedType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PolicyReference", scope = CommissionType.class)
    public JAXBElement<PolicyReferenceType> createCommissionTypePolicyReference(PolicyReferenceType value) {
        return new JAXBElement<PolicyReferenceType>(_CommissionTypePolicyReference_QNAME, PolicyReferenceType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetCommissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetCommission", scope = CommissionType.class)
    public JAXBElement<NetCommissionType> createCommissionTypeNetCommission(NetCommissionType value) {
        return new JAXBElement<NetCommissionType>(_CommissionTypeNetCommission_QNAME, NetCommissionType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsCommPlanTiredType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsCommPlanTired", scope = CommissionType.class)
    public JAXBElement<IsCommPlanTiredType> createCommissionTypeIsCommPlanTired(IsCommPlanTiredType value) {
        return new JAXBElement<IsCommPlanTiredType>(_CommissionTypeIsCommPlanTired_QNAME, IsCommPlanTiredType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type", scope = CommissionType.class)
    public JAXBElement<TypeType> createCommissionTypeType(TypeType value) {
        return new JAXBElement<TypeType>(_CommissionTypeType_QNAME, TypeType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsCommPlanPercentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsCommPlanPercent", scope = CommissionType.class)
    public JAXBElement<IsCommPlanPercentType> createCommissionTypeIsCommPlanPercent(IsCommPlanPercentType value) {
        return new JAXBElement<IsCommPlanPercentType>(_CommissionTypeIsCommPlanPercent_QNAME, IsCommPlanPercentType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Id", scope = CommissionType.class)
    public JAXBElement<IdType> createCommissionTypeId(IdType value) {
        return new JAXBElement<IdType>(_CommissionTypeId_QNAME, IdType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducerCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProducerCode", scope = CommissionType.class)
    public JAXBElement<ProducerCodeType> createCommissionTypeProducerCode(ProducerCodeType value) {
        return new JAXBElement<ProducerCodeType>(_CommissionTypeProducerCode_QNAME, ProducerCodeType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateModifiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateModified", scope = CommissionType.class)
    public JAXBElement<DateModifiedType> createCommissionTypeDateModified(DateModifiedType value) {
        return new JAXBElement<DateModifiedType>(_CommissionTypeDateModified_QNAME, DateModifiedType.class, CommissionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommPlanIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CommPlanId", scope = CommissionType.class)
    public JAXBElement<CommPlanIdType> createCommissionTypeCommPlanId(CommPlanIdType value) {
        return new JAXBElement<CommPlanIdType>(_CommissionTypeCommPlanId_QNAME, CommPlanIdType.class, CommissionType.class, value);
    }

}
