//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PolicyUnderwriterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyUnderwriterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnderwriterCode" type="{}UnderwriterCodeType"/>
 *         &lt;element name="UnderwriterName" type="{}UnderwriterNameType"/>
 *         &lt;element name="UnderWriterAddressList" type="{}UnderWriterAddressListType"/>
 *         &lt;element name="UnderwriterContactList" type="{}UnderwriterContactListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="EntityReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Gid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RefName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RefValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyUnderwriterType", propOrder = {
    "underwriterCode",
    "underwriterName",
    "underWriterAddressList",
    "underwriterContactList"
})
public class PolicyUnderwriterType {

    @XmlElement(name = "UnderwriterCode", required = true)
    protected UnderwriterCodeType underwriterCode;
    @XmlElement(name = "UnderwriterName", required = true)
    protected UnderwriterNameType underwriterName;
    @XmlElement(name = "UnderWriterAddressList", required = true)
    protected UnderWriterAddressListType underWriterAddressList;
    @XmlElement(name = "UnderwriterContactList", required = true)
    protected UnderwriterContactListType underwriterContactList;
    @XmlAttribute(name = "DateCreated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreated;
    @XmlAttribute(name = "EntityReference")
    protected String entityReference;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "Gid")
    protected Integer gid;
    @XmlAttribute(name = "Id")
    protected Integer id;
    @XmlAttribute(name = "RefName")
    protected String refName;
    @XmlAttribute(name = "RefValue")
    protected Integer refValue;
    @XmlAttribute(name = "UserCreated")
    protected String userCreated;

    /**
     * Gets the value of the underwriterCode property.
     * 
     * @return
     *     possible object is
     *     {@link UnderwriterCodeType }
     *     
     */
    public UnderwriterCodeType getUnderwriterCode() {
        return underwriterCode;
    }

    /**
     * Sets the value of the underwriterCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderwriterCodeType }
     *     
     */
    public void setUnderwriterCode(UnderwriterCodeType value) {
        this.underwriterCode = value;
    }

    /**
     * Gets the value of the underwriterName property.
     * 
     * @return
     *     possible object is
     *     {@link UnderwriterNameType }
     *     
     */
    public UnderwriterNameType getUnderwriterName() {
        return underwriterName;
    }

    /**
     * Sets the value of the underwriterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderwriterNameType }
     *     
     */
    public void setUnderwriterName(UnderwriterNameType value) {
        this.underwriterName = value;
    }

    /**
     * Gets the value of the underWriterAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link UnderWriterAddressListType }
     *     
     */
    public UnderWriterAddressListType getUnderWriterAddressList() {
        return underWriterAddressList;
    }

    /**
     * Sets the value of the underWriterAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderWriterAddressListType }
     *     
     */
    public void setUnderWriterAddressList(UnderWriterAddressListType value) {
        this.underWriterAddressList = value;
    }

    /**
     * Gets the value of the underwriterContactList property.
     * 
     * @return
     *     possible object is
     *     {@link UnderwriterContactListType }
     *     
     */
    public UnderwriterContactListType getUnderwriterContactList() {
        return underwriterContactList;
    }

    /**
     * Sets the value of the underwriterContactList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderwriterContactListType }
     *     
     */
    public void setUnderwriterContactList(UnderwriterContactListType value) {
        this.underwriterContactList = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the entityReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityReference() {
        return entityReference;
    }

    /**
     * Sets the value of the entityReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityReference(String value) {
        this.entityReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGid(Integer value) {
        this.gid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the refValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefValue() {
        return refValue;
    }

    /**
     * Sets the value of the refValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefValue(Integer value) {
        this.refValue = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

}
