//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:43 AM EDT 
//


package com.ameet.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RulesetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RulesetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyReference" type="{}PolicyReferenceType"/>
 *         &lt;element name="EntityType" type="{}EntityTypeType"/>
 *         &lt;element name="RulesetExecId" type="{}RulesetExecIdType"/>
 *         &lt;element name="RulesetId" type="{}RulesetIdType"/>
 *         &lt;element name="ActionStatus" type="{}ActionStatusType"/>
 *         &lt;element name="ActionDesc" type="{}ActionDescType"/>
 *         &lt;element name="UserRemarks" type="{}UserRemarksType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RulesetType", propOrder = {
    "policyReference",
    "entityType",
    "rulesetExecId",
    "rulesetId",
    "actionStatus",
    "actionDesc",
    "userRemarks"
})
public class RulesetType {

    @XmlElement(name = "PolicyReference", required = true)
    protected PolicyReferenceType policyReference;
    @XmlElement(name = "EntityType", required = true)
    protected EntityTypeType entityType;
    @XmlElement(name = "RulesetExecId", required = true)
    protected RulesetExecIdType rulesetExecId;
    @XmlElement(name = "RulesetId", required = true)
    protected RulesetIdType rulesetId;
    @XmlElement(name = "ActionStatus", required = true)
    protected ActionStatusType actionStatus;
    @XmlElement(name = "ActionDesc", required = true)
    protected ActionDescType actionDesc;
    @XmlElement(name = "UserRemarks", required = true)
    protected UserRemarksType userRemarks;

    /**
     * Gets the value of the policyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyReferenceType }
     *     
     */
    public PolicyReferenceType getPolicyReference() {
        return policyReference;
    }

    /**
     * Sets the value of the policyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyReferenceType }
     *     
     */
    public void setPolicyReference(PolicyReferenceType value) {
        this.policyReference = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityTypeType }
     *     
     */
    public EntityTypeType getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityTypeType }
     *     
     */
    public void setEntityType(EntityTypeType value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the rulesetExecId property.
     * 
     * @return
     *     possible object is
     *     {@link RulesetExecIdType }
     *     
     */
    public RulesetExecIdType getRulesetExecId() {
        return rulesetExecId;
    }

    /**
     * Sets the value of the rulesetExecId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesetExecIdType }
     *     
     */
    public void setRulesetExecId(RulesetExecIdType value) {
        this.rulesetExecId = value;
    }

    /**
     * Gets the value of the rulesetId property.
     * 
     * @return
     *     possible object is
     *     {@link RulesetIdType }
     *     
     */
    public RulesetIdType getRulesetId() {
        return rulesetId;
    }

    /**
     * Sets the value of the rulesetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesetIdType }
     *     
     */
    public void setRulesetId(RulesetIdType value) {
        this.rulesetId = value;
    }

    /**
     * Gets the value of the actionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatusType }
     *     
     */
    public ActionStatusType getActionStatus() {
        return actionStatus;
    }

    /**
     * Sets the value of the actionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatusType }
     *     
     */
    public void setActionStatus(ActionStatusType value) {
        this.actionStatus = value;
    }

    /**
     * Gets the value of the actionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDescType }
     *     
     */
    public ActionDescType getActionDesc() {
        return actionDesc;
    }

    /**
     * Sets the value of the actionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDescType }
     *     
     */
    public void setActionDesc(ActionDescType value) {
        this.actionDesc = value;
    }

    /**
     * Gets the value of the userRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link UserRemarksType }
     *     
     */
    public UserRemarksType getUserRemarks() {
        return userRemarks;
    }

    /**
     * Sets the value of the userRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRemarksType }
     *     
     */
    public void setUserRemarks(UserRemarksType value) {
        this.userRemarks = value;
    }

}
